window.pageTranslations = {
    en: {
        "sound_page_title": "Naad Brahma | Cosmic Resonance & Vedic Alignment | MAHADEV ASTROLOGER MA",
        "sound_hero_title": "Naad Brahma",
        "sound_hero_quote": "The Eternal Union of Cosmic Sound & Planetary Stars",
        "sound_intro_para": "Experience the profound science of Naad Brahma. Our platform explores the sacred resonance between ancient Vedic sound patterns, your biological Doshas, and the mathematical frequencies of the cosmos.",
        "btn_read_article": "Explore The Divine Science ➔",
        "dosha_section_title": "Identify Your Cosmic Resonance",
        "quiz_instruction": "Analyze your lifestyle and habits to find your primary Dosha (Vata, Pitta, or Kapha).",
        "btn_start_quiz": "Analyze My Cosmic Energy",
        "matrix_title": "Planetary Frequency Matrix",
        "col_planet": "Planet",
        "col_raag": "Suggested Raag",
        "col_status": "Resonance Frequency",
        "art_main_title": "Naad Brahma: The Cosmic Symphony",
        "art_para_1": "In ancient Vedic tradition, \"Naad\" represents the primordial vibration that gave birth to the universe. Our bodies, being a micro-cosmos, respond to these same celestial frequencies. By understanding your birth chart and your biological constitution (Doshas), we can identify which sound patterns (Raags) will bring you back into a state of 'Samattva' (Balance).",
        "art_sub_1": "The Mechanics of Sound Alignment",
        "art_para_2": "Modern science is now acknowledging what Sages knew thousands of years ago: frequency determines the state of matter. By listening to specifically curated Vedic chants or Raags during your \"Auspicious Hours\", you can align your individual pulse with the cosmic rhythm of the stars. This is not just sound; it is the spiritual technology of MAHADEV ASTROLOGER MA.",
        "new_art_footer_quote": "\"Sound is the divine nectar of the future, when aligned with the position of your stars.\"",
        "benefits_title": "Spiritual Advantages",
        "benefit_1": "<strong>Enhanced Clarity:</strong> Achieve mental focus by synchronizing with planetary sound patterns.",
        "benefit_2": "<strong>Energy Regulation:</strong> Balance your Pitta, Vata, or Kapha through specific harmonic frequencies.",
        "benefit_3": "<strong>Vedic Peace:</strong> Reconnect with your ancestral roots through the primordial sound of 'Om'."
    },
    hi: {
        "sound_page_title": "नाद ब्रह्म | कॉस्मिक रेजोनेंस और वैदिक अलाइनमेंट | MAHADEV ASTROLOGER MA",
        "sound_hero_title": "नाद ब्रह्म",
        "sound_hero_quote": "ब्रह्मांडीय ध्वनि और ग्रहों का शाश्वत मिलन",
        "sound_intro_para": "नाद ब्रह्म के गहन विज्ञान का अनुभव करें। हमारा मंच प्राचीन वैदिक ध्वनि स्वरूपों, आपके जैविक दोषों और ब्रह्मांड की गणितीय आवृत्तियों के बीच पवित्र प्रतिध्वनि की खोज करता है।",
        "btn_read_article": "दिव्य विज्ञान खोजें ➔",
        "dosha_section_title": "अपना दोष पहचानें",
        "quiz_instruction": "अपने प्राथमिक दोष (वात, पित्त, या कफ) को खोजने के लिए अपनी जीवन शैली और आदतों का विश्लेषण करें।",
        "btn_start_quiz": "मेरी ब्रह्मांडीय ऊर्जा का विश्लेषण करें",
        "matrix_title": "ग्रह तरंग सारणी",
        "col_planet": "ग्रह",
        "col_raag": "सुझाया गया राग",
        "col_status": "प्रभाव",
        "art_main_title": "नाद ब्रह्म का विज्ञान",
        "art_para_1": "प्राचीन वैदिक परंपरा में, \"नाद\" उस मौलिक कंपन का प्रतिनिधित्व करता है जिसने ब्रह्मांड को जन्म दिया। हमारा शरीर, एक सूक्ष्म ब्रह्मांड होने के नाते, इन्हीं खगोलीय आवृत्तियों के प्रति प्रतिक्रिया करता है। आपकी जन्म कुंडली और जैविक प्रकृति (दोष) को समझकर, हम उन ध्वनि स्वरूपों (रागों) की पहचान कर सकते हैं जो आपको 'समत्व' (संतुलन) की स्थिति में वापस लाएंगे।",
        "art_sub_1": "ऊर्जा का अलाइनमेंट",
        "art_para_2": "आधुनिक विज्ञान अब उस बात को स्वीकार कर रहा है जो ऋषि-मुनि हजारों साल पहले जानते थे: आवृत्ति पदार्थ की स्थिति निर्धारित करती है। अपने \"शुभ समय\" के दौरान विशेष रूप से तैयार किए गए वैदिक मंत्रों या रागों को सुनकर, आप अपनी व्यक्तिगत नाड़ी को तारों की ब्रह्मांडीय लय के साथ जोड़ सकते हैं। यह केवल ध्वनि नहीं है; यह MAHADEV ASTROLOGER MA की आध्यात्मिक तकनीक है।",
        "new_art_footer_quote": "\"नाद (ध्वनि) भविष्य का दिव्य अमृत है, जब इसे आपके नक्षत्रों की स्थिति के साथ जोड़ा जाए।\"",
        "benefits_title": "संतुलन के लाभ",
        "benefit_1": "<strong>मानसिक स्पष्टता:</strong> ग्रहों की ध्वनि तरंगों के साथ जुड़कर मानसिक एकाग्रता प्राप्त करें।",
        "benefit_2": "<strong>ऊर्जा नियमन:</strong> विशिष्ट हार्मोनिक आवृत्तियों के माध्यम से अपने वात, पित्त या कफ को संतुलित करें।",
        "benefit_3": "<strong>वैदिक शांति:</strong> 'ओम' की मौलिक ध्वनि के माध्यम से अपनी पैतृक जड़ों से पुनः जुड़ें।"
    }
};
