window.pageTranslations = {
    en: {
        "horoscope_page_title": "Daily Horoscope & Rashifal 2026 | Mahadev Astrologer M A",
        "horoscope_title": "Daily Horoscope",
        "horo_intro_desc": "The movement of celestial planets determines the direction of our lives. At Mahadev Astrologer M A's horoscope portal, we provide accurate daily analysis based on Moon Signs and planetary transits. Whether your sign is Aries or Pisces, here you can gain divine insights from Mahadev regarding your career, health, and love life.",
        "horoscope_subtitle": "Choose your zodiac and get today's guidance",
         horo_career: "Career & Finance", horo_love: "Love & Family", horo_health: "Health & Wellness", horo_remedy: "Vedic Remedy", expert_note: "Expert Note",

        "finder_title": "🔱 Identify Your Zodiac (Rashi Finder)",
        "finder_name_label": "By First Letter of Name:",
        "finder_select": "Select...",
        "finder_date_label": "By Date & Month of Birth:",
        "zod_aries": "Aries",
        "zod_taurus": "Taurus",
        "zod_gemini": "Gemini",
        "zod_cancer": "Cancer",
        "zod_leo": "Leo",
        "zod_virgo": "Virgo",
        "zod_libra": "Libra",
        "zod_scorpio": "Scorpio",
        "zod_sagittarius": "Sagittarius",
        "zod_capricorn": "Capricorn",
        "zod_aquarius": "Aquarius",
        "zod_pisces": "Pisces",
        "edu_title": "Importance of Horoscope & Vedic Astrology",
        "edu_moon_h": "Influence of Moon Sign",
        "edu_moon_p": "In Vedic Astrology, horoscopes are always viewed based on the 'Moon Sign' because the Moon rules our mind and emotions.",
        "edu_guide_h": "Why Daily Guidance?",
        "edu_guide_p": "By understanding planetary transits, you can better plan your day and adopt 'Mahadev's Remedies' for upcoming obstacles.",
        "edu_finder_h": "Sign Finder (Magic Tool)",
        "edu_finder_p": "If you don't know your zodiac sign, use our 'Magic Finder' tool. it helps identify your correct sign based on your name or date of birth.",
        "faq_main_title": "Frequently Asked Questions (FAQ)",
        "faq_q1": "Is the horoscope 100% accurate?",
        "faq_a1": "No, daily horoscopes are general calculations based on transits. For 100% accuracy, a personal Birth Chart is essential.",
        "faq_q2": "What to do if the horoscope doesn't match?",
        "faq_a2": "If the results don't align, your 'Mahadasha' might be more dominant. In such cases, you should get a birth chart or palm analysis.",
        "faq_q3": "Which is better: Birth Chart or Palmistry?",
        "faq_a3": "A birth chart is best if birth time is known; otherwise, Palmistry becomes a reliable source of guidance by the grace of Mahadev.",
        "faq_footer_note": "* MAHADEV ASTROLOGER M A aims to alert you through astrological signs. We suggest taking this as guidance only."
    },
    hi: {
        "horoscope_page_title": "दैनिक राशिफल 2026 | Mahadev Astrologer M A",
        "horoscope_title": "दैनिक राशिफल",
        "horo_intro_desc": "आकाशीय ग्रहों की चाल हमारे जीवन की दिशा निर्धारित करती है। Mahadev Astrologer M A के इस राशिफल पोर्टल पर हम चंद्र राशि (Moon Sign) और ग्रहों के गोचर के आधार पर सटीक दैनिक विश्लेषण प्रदान करते हैं। चाहे आपकी राशि मेष हो या मीन, यहाँ आप अपने करियर, स्वास्थ्य, और प्रेम जीवन से जुड़ी महादेव की दिव्य अंतर्दृष्टि प्राप्त कर सकते हैं।",
        "horoscope_subtitle": "अपनी राशि चुनें और आज का परामर्श प्राप्त करें",
         horo_career: "करियर और वित्त", horo_love: "प्रेम और परिवार", horo_health: "स्वास्थ्य और कल्याण",horo_remedy: "वैदिक अचूक उपाय", expert_note: "विशेषज्ञ की टिप्पणी",
        "finder_title": "🔱 अपना राशि पहचानें (Rashi Finder)",
        "finder_name_label": "नाम के पहले अक्षर से:",
        "finder_select": "चुनें...",
        "finder_date_label": "जन्म तिथि और महीने से:",
        "zod_aries": "मेष",
        "zod_taurus": "वृषभ",
        "zod_gemini": "मिथुन",
        "zod_cancer": "कर्क",
        "zod_leo": "सिंह",
        "zod_virgo": "कन्या",
        "zod_libra": "तुला",
        "zod_scorpio": "वृश्चिक",
        "zod_sagittarius": "धनु",
        "zod_capricorn": "मकर",
        "zod_aquarius": "कुंभ",
        "zod_pisces": "मीन",
        "edu_title": "राशिफल और वैदिक ज्योतिष का महत्व",
        "edu_moon_h": "चंद्र राशि का प्रभाव",
        "edu_moon_p": "वैदिक ज्योतिष में राशिफल हमेशा 'चंद्र राशि' (Moon Sign) के आधार पर देखा जाता है, क्योंकि चंद्रमा हमारे मन और भावनाओं का स्वामी है।",
        "edu_guide_h": "दैनिक मार्गदर्शन क्यों?",
        "edu_guide_p": "ग्रहों के गोचर (Transit) को समझकर आप अपने दिन की योजना बेहतर बना सकते हैं और आने वाली बाधाओं के लिए 'महादेव के उपाय' अपना सकते हैं।",
        "edu_finder_h": "राशि पहचान (Finder Tool)",
        "edu_finder_p": "अगर आप अपनी राशि नहीं जानते, तो हमारे 'Magic Finder' टूल का उपयोग करें। यह आपके नाम या जन्म तिथि से सही राशि बताता है।",
        "faq_main_title": "मह महत्वपूर्ण प्रश्न और स्पष्टीकरण (FAQ)",
        "faq_q1": "क्या राशिफल 100% सटीक होता है?",
        "faq_a1": "नहीं, दैनिक राशिफल गोचर पर आधारित सामान्य गणना है। 100% सटीकता के लिए व्यक्तिगत जन्म कुंडली (Birth Chart) का होना अनिवार्य है।",
        "faq_q2": "अगर राशिफल मैच न हो तो क्या करें?",
        "faq_a2": "यदि परिणाम मेल नहीं खा रहे, तो आपकी कुंडली की 'महादशा' अधिक प्रभावी हो सकती है। ऐसी स्थिति में कुंडली या हस्तरेखा का विश्लेषण करवाना चाहिए।",
        "faq_q3": "कुंडली या हस्तरेखा: क्या बेहतर है?",
        "faq_a3": "जन्म समय ज्ञात होने पर कुंडली श्रेष्ठ है, अन्यथा हस्तरेखा (Palmistry) महादेव के आशीर्वाद से सटीक मार्गदर्शन का जरिया बनती है।",
        "faq_footer_note": "* MAHADEV ASTROLOGER M A का उद्देश्य आपको ज्योतिषीय संकेतों के माध्यम से सचेत करना है।"
    }
};
