window.pageTranslations = {
    en: {
        "ins_panchang_title": "Daily Panchang 2026",
        "pan_intro_h1": "Today's Panchang & Vedic Calculations",
        "pan_intro_p": "Panchang holds special significance in Vedic Astrology. It is a precise combination of Tithi, Nakshatra, Yoga, Karana, and Var. Through this special Panchang by Mahadev Astrologer MA, you can get accurate information on daily auspicious Muhurats, Rahukaal, and Choghadiya. Our aim is to make you aware of the correct cycle of time by the grace of Mahadev, so that you can make every endeavor successful and auspicious.",
       // In keys ko HTML ke data-key se match kiya gaya hai
"tithi": "Tithi",
"nakshatra": "Nakshatra",
"yoga": "Yoga",
"karan": "Karan",
"paksha": "Paksha",
"sunrise": "Sun Rise/Set",
"abhijit": "Abhijit Muhurat",
"rahukaal": "Rahu Kaal",
"ph_time": "Time",
"pan_name": "Muhurat",
"ph_nature": "Nature"
        "day_sun": "Sun",
        "day_mon": "Mon",
        "day_tue": "Tue",
        "day_wed": "Wed",
        "day_thu": "Thu",
        "day_fri": "Fri",
        "day_sat": "Sat",
        "nav_event": "Festivals & Events",
        "pan_info_elements_h": "Five Elements of Panchang",
        "pan_info_elements_p": "Panchang is primarily composed of five elements: Tithi, Var, Nakshatra, Yoga, and Karana. By choosing them correctly, we can achieve success in our endeavors.",
        "pan_info_muhurat_h": "Choghadiya & Muhurat",
        "pan_info_muhurat_p": "Knowledge of Choghadiya is essential for auspicious tasks. Amrit, Shubh, Labh, and Char are considered auspicious, while Rog, Udveg, and Kaal should be avoided.",
        "pan_info_vedic_h": "Vedic Guidance",
        "pan_info_vedic_p": "The positions of planets have a deep impact on our lives. Through this path of knowledge from MAHADEV ASTROLOGER MA, we can balance our future.",
        "pan_faq_title": "Special Information on Panchang & Muhurat (FAQ)",
        "pan_q1": "Why is there a time difference according to location?",
        "pan_a1": "Panchang calculations are based on Sunrise. Since Sunrise time varies in every city, there may be a few minutes' difference in Rahukaal and auspicious Muhurats. The calculations provided here are based on a standard time.",
        "pan_q2": "What is the importance of Abhijit Muhurat?",
        "pan_a2": "According to scriptures, Abhijit Muhurat is considered the most auspicious time of the day. Any work started during this time is successful with the blessings of Mahadev. If you cannot find a specific Muhurat, you can use this time.",
        "pan_disclaimer": "* This Panchang is based on Vedic mathematics. For accurate personal Muhurats, consult MAHADEV ASTROLOGER MA.",
        
        // Essential Dynamic Panchang Data (Included for page functionality)
        "paksha_shukla": "Shukla Paksha", "paksha_krishna": "Krishna Paksha",
          // ===== Month Name (EN) =====
        "mon_jan": "January", "mon_feb": "February", "mon_mar": "March", "mon_apr": "April", "mon_may": "May", "mon_jun": "June", "mon_jul": "July", "mon_aug": "August", "mon_sep": "September", "mon_oct": "October", "mon_nov": "November", "mon_dec": "December",
        "no_events": "No festivals today",
         // Choghadiya
        "chaug_char": "Char", "chaug_labh": "Labh", "chaug_amrit": "Amrit", "chaug_shubh": "Shubh", "chaug_rog": "Rog", "chaug_kaal": "Kaal", "chaug_udveg": "Udveg",
        "bad": "Bad", "neutral": "Neutral", "good": "Good",
           // Tithis
        "tithi_01": "Pratipada", "tithi_02": "Dwitiya", "tithi_03": "Tritiya", "tithi_04": "Chaturthi", "tithi_05": "Panchami", "tithi_06": "Shashthi", "tithi_07": "Saptami", "tithi_08": "Ashtami", "tithi_09": "Navami", "tithi_10": "Dashami", "tithi_11": "Ekadashi", "tithi_12": "Dwadashi", "tithi_13": "Trayodashi", "tithi_14": "Chaturdashi", "tithi_15": "Purnima", "tithi_30": "Amavasya",
          // Yoga & Karana
        "yoga_01": "Vishkumbha", "yoga_02": "Priti", "yoga_03": "Ayushman", "yoga_04": "Saubhagya", "yoga_05": "Shobhana", "yoga_06": "Atiganda", "yoga_07": "Sukarma", "yoga_08": "Dhriti", "yoga_09": "Shoola", "yoga_10": "Ganda", "yoga_11": "Vriddhi", "yoga_12": "Dhruva", "yoga_13": "Vyaghata", "yoga_14": "Harshana", "yoga_15": "Vajra", "yoga_16": "Siddhi", "yoga_17": "Vyatipata", "yoga_18": "Variyana", "yoga_19": "Parigha", "yoga_20": "Shiva", "yoga_21": "Siddha", "yoga_22": "Sadhya", "yoga_23": "Shubha", "yoga_24": "Shukla", "yoga_25": "Brahma", "yoga_26": "Indra", "yoga_27": "Vaidhriti",
        "karan_01": "Bava", "karan_02": "Balava", "karan_03": "Kaulava", "karan_04": "Taitila", "karan_05": "Gara", "karan_06": "Vanija", "karan_07": "Vishti", "karan_08": "Shakuni", "karan_09": "Chatushpada", "karan_10": "Naga", "karan_11": "Kimstughna"
        "ph_time": "Time", "pan_name": "Muhurat", "ph_status": "Status", "nav_event":"Festivals & Events", "ph_nature": "Nature",
    // --- Panchang Knowledge Section ---
"pan_info_elements_h": "Five Elements of Panchang",
"pan_info_elements_p": "Panchang is primarily composed of five elements: Tithi, Var, Nakshatra, Yoga, and Karana. By choosing them correctly, we can achieve success in our endeavors.",
"pan_info_muhurat_h": "Choghadiya & Muhurat",
"pan_info_muhurat_p": "Knowledge of Choghadiya is essential for auspicious tasks. Amrit, Shubh, Labh, and Char are considered auspicious, while Rog, Udveg, and Kaal should be avoided.",
"pan_info_vedic_h": "Vedic Guidance",
"pan_info_vedic_p": "The positions of planets have a deep impact on our lives. Through this path of knowledge from MAHADEV ASTROLOGER MA, we can balance our future.",
   // --- Panchang FAQ Section ---
"pan_faq_title": "Special Information on Panchang & Muhurat (FAQ)",
"pan_q1": "Why is there a time difference according to location?",
"pan_a1": "Panchang calculations are based on Sunrise. Since Sunrise time varies in every city, there may be a few minutes' difference in Rahukaal and auspicious Muhurats. The calculations provided here are based on a standard time.",
"pan_q2": "What is the importance of Abhijit Muhurat?",
"pan_a2": "According to scriptures, Abhijit Muhurat is considered the most auspicious time of the day. Any work started during this time is successful with the blessings of Mahadev. If you cannot find a specific Muhurat, you can use this time.",
"pan_disclaimer": "* This Panchang is based on Vedic mathematics. For accurate personal Muhurats, consult MAHADEV ASTROLOGER MA.",
    }, 
    
  hi: {
        "ins_panchang_title": "दैनिक पंचांग 2026",
        "pan_intro_h1": "आज का पंचांग और वैदिक गणना",
        "pan_intro_p": "वैदिक ज्योतिष में पंचांग का विशेष महत्व है। यह तिथि, नक्षत्र, योग, करण और वार का सटीक मेल है। <strong>Mahadev Astrologer MA</strong> के इस विशेष पंचांग के माध्यम से आप दैनिक शुभ मुहूर्त, राहुकाल और चौघड़िया की सटीक जानकारी प्राप्त कर सकते हैं। हमारा उद्देश्य महादेव की कृपा से आपको समय के सही चक्र से अवगत कराना है, ताकि आप अपने प्रत्येक कार्य को सफल और मंगलमय बना सकें।",
       "tithi": "तिथि",
       "nakshatra": "नक्षत्र",
       "yoga": "योग",
       "karan": "करण",
       "paksha": "पक्ष",
       "sunrise": "सूर्योदय/अस्त",
       "abhijit": "अभिजीत मुहूर्त",
       "rahukaal": "राहुकाल",
       "ph_time": "समय",
       "pan_name": "मुहूर्त",
       "ph_nature": "प्रकृति",       
        "day_sun": "रवि",
        "day_mon": "सोम",
        "day_tue": "मंगल",
        "day_wed": "बुध",
        "day_thu": "गुरु",
        "day_fri": "शुक्र",
        "day_sat": "शनि",
        "nav_event": "त्यौहार और इवेंट्स",
        "pan_info_elements_h": "पंचांग के पांच अंग",
        "pan_info_elements_p": "पंचांग मुख्य रूप से पांच तत्वों से बना है: तिथि, वार, नक्षत्र, योग और करण। इनके सही चयन से हम अपने कार्यों में सिद्धि प्राप्त कर सकते हैं।",
        "pan_info_muhurat_h": "चौघड़िया और मुहूर्त",
        "pan_info_muhurat_p": "शुभ कार्यों के लिए चौघड़िया का ज्ञान आवश्यक है। अमृत, शुभ, लाभ और चर को शुभ माना जाता है, जबकि रोग, उद्वेग और काल से बचना चाहिए।",
        "pan_info_vedic_h": "वैदिक मार्गदर्शन",
        "pan_info_vedic_p": "ग्रहों की स्थिति हमारे जीवन पर गहरा प्रभाव डालती है। <strong>MAHADEV ASTROLOGER MA</strong> के इस ज्ञान मार्ग से हम अपने भविष्य को संतुलित कर सकते हैं।",
        "pan_faq_title": "पंचांग और मुहूर्त संबंधी विशेष जानकारी (FAQ)",
        "pan_q1": "स्थान के अनुसार समय में अंतर क्यों?",
        "pan_a1": "पंचांग की गणना सूर्योदय (Sunrise) पर आधारित होती है। हर शहर में सूर्योदय का समय अलग होता है, इसलिए राहुकाल और शुभ मुहूर्त के समय में कुछ मिनटों का अंतर आ सकता है। यहाँ दी गई गणना एक मानक समय पर आधारित है।",
        "pan_q2": "अभिजीत मुहूर्त का महत्व क्या है?",
        "pan_a2": "शास्त्रों के अनुसार, अभिजीत मुहूर्त दिन का सबसे शुभ समय माना जाता है। इसमें शुरू किया गया कोई भी कार्य महादेव के आशीर्वाद से सफल होता है। यदि आपको कोई विशेष मुहूर्त न मिल रहा हो, तो आप इस समय का उपयोग कर सकते हैं।",
        "pan_disclaimer": "* यह पंचांग वैदिक गणित पर आधारित है। सटीक व्यक्तिगत मुहूर्त के लिए <strong>MAHADEV ASTROLOGER MA</strong> से परामर्श लें।",

        // Essential Dynamic Panchang Data (Included for page functionality)
        "paksha_shukla": "शुक्ल पक्ष", "paksha_krishna": "कृष्ण पक्ष",
         "ph_time": "समय", "pan_name": "मुहूर्त", "ph_status": "स्थिति", "nav_event": "त्यौहार और इवेंट्स", "ph_nature": "प्रकृति",
           // ===== Montn Name (HI) =====
      "mon_jan": "जनवरी", "mon_feb": "फरवरी", "mon_mar": "मार्च", "mon_apr": "अप्रैल", "mon_may": "मई", "mon_jun": "जून", "mon_jul": "जुलाई", "mon_aug": "अगस्त", "mon_sep": "सितंबर", "mon_oct": "अक्टूबर", "mon_nov": "नवंबर", "mon_dec": "दिसंबर",
        "no_events": "आज कोई त्यौहार नहीं है",
           // Choghadiya
        "chaug_char": "चर", "chaug_labh": "लाभ", "chaug_amrit": "अमृत", "chaug_shubh": "शुभ", "chaug_rog": "रोग", "chaug_kaal": "काल", "chaug_udveg": "उद्वेग",
        "bad": "अशुभ", "neutral": "सामान्य", "good": "शुभ",
          // Tithis
        "tithi_01": "प्रतिपदा", "tithi_02": "द्वितीया", "tithi_03": "तृतीया", "tithi_04": "चतुर्थी", "tithi_05": "पंचमी", "tithi_06": "षष्ठी", "tithi_07": "सप्तमी", "tithi_08": "अष्टमी", "tithi_09": "नवमी", "tithi_10": "दशमी", "tithi_11": "एकादशी", "tithi_12": "द्वादशी", "tithi_13": "त्रयोदशी", "tithi_14": "चतुर्दशी", "tithi_15": "पूर्णिमा", "tithi_30": "अमावस्या",
         // Yoga & Karana
        "yoga_01": "विष्कुम्भ", "yoga_02": "प्रीति", "yoga_03": "आयुष्मान", "yoga_04": "सौभाग्य", "yoga_05": "शोभन", "yoga_06": "अतिगण्ड", "yoga_07": "सुकर्मा", "yoga_08": "धृति", "yoga_09": "शूल", "yoga_10": "गण्ड", "yoga_11": "वृद्धि", "yoga_12": "ध्रुव", "yoga_13": "व्याघात", "yoga_14": "हर्षण", "yoga_15": "वज्र", "yoga_16": "सिद्धि", "yoga_17": "व्यतिपात", "yoga_18": "वरीयान", "yoga_19": "परिघ", "yoga_20": "शिव", "yoga_21": "सिद्ध", "yoga_22": "साध्य", "yoga_23": "शुभ", "yoga_24": "शुक्ल", "yoga_25": "ब्रह्म", "yoga_26": "इन्द्र", "yoga_27": "वैधृति",
        "karan_01": "बव", "karan_02": "बालव", "karan_03": "कौलव", "karan_04": "तैतिल", "karan_05": "गर", "karan_06": "वणिज", "karan_07": "विष्टि", "karan_08": "शकुनि", "karan_09": "चतुष्पाद", "karan_10": "नाग", "karan_11": "किस्तुघ्न",
  // --- Panchang Knowledge Section ---
"pan_info_elements_h": "पंचांग के पांच अंग",
"pan_info_elements_p": "पंचांग मुख्य रूप से पांच तत्वों से बना है: तिथि, वार, नक्षत्र, योग और करण। इनके सही चयन से हम अपने कार्यों में सिद्धि प्राप्त कर सकते हैं।",
"pan_info_muhurat_h": "चौघड़िया और मुहूर्त",
"pan_info_muhurat_p": "शुभ कार्यों के लिए चौघड़िया का ज्ञान आवश्यक है। अमृत, शुभ, लाभ और चर को शुभ माना जाता है, जबकि रोग, उद्वेग और काल से बचना चाहिए।",
"pan_info_vedic_h": "वैदिक मार्गदर्शन",
"pan_info_vedic_p": "ग्रहों की स्थिति हमारे जीवन पर गहरा प्रभाव डालती है। <strong>MAHADEV ASTROLOGER MA</strong> के इस ज्ञान मार्ग से हम अपने भविष्य को संतुलित कर सकते हैं।",
// --- Panchang FAQ Section ---
"pan_faq_title": "पंचांग और मुहूर्त संबंधी विशेष जानकारी (FAQ)",
"pan_q1": "स्थान के अनुसार समय में अंतर क्यों?",
"pan_a1": "पंचांग की गणना सूर्योदय (Sunrise) पर आधारित होती है। हर शहर में सूर्योदय का समय अलग होता है, इसलिए राहुकाल और शुभ मुहूर्त के समय में कुछ मिनटों का अंतर आ सकता है। यहाँ दी गई गणना एक मानक समय पर आधारित है।",
"pan_q2": "अभिजीत मुहूर्त का महत्व क्या है?",
"pan_a2": "शास्त्रों के अनुसार, अभिजीत मुहूर्त दिन का सबसे शुभ समय माना जाता है। इसमें शुरू किया गया कोई भी कार्य महादेव के आशीर्वाद से सफल होता है। यदि आपको कोई विशेष मुहूर्त न मिल रहा हो, तो आप इस समय का उपयोग कर सकते हैं।",
"pan_disclaimer": "* यह पंचांग वैदिक गणित पर आधारित है। सटीक व्यक्तिगत मुहूर्त के लिए <strong>MAHADEV ASTROLOGER MA</strong> से परामर्श लें।",

  }
};
