window.pageTranslations = {
    en: {
        "guide_title": "Latest Divine Guide",
        "guide_subtitle": "Ancient Wisdom for Modern Life",
        "btn_view_more": "VIEW MORE GUIDES 🔱",
       
        "ab_title": "🔱 Ayushman Bhava",
        "ab_desc": "Accurately measure your daily water and energy (steps) requirements according to Ayurveda and Sound Science.",
        "ab_q1": "1. Your Height (in cm)",
        "ab_q2": "2. Your Weight (in kg)",
        "ab_btn": "CHECK MY HEALTH ➔",
        "ab_res_title": "Your Daily Requirement",
        "ab_lbl_water": "Water",
        "ab_lbl_steps": "Steps",
        "ab_lbl_bmi": "Body Index",
        "ab_rem_title": "🌿 Vedic Daily Routine Sutras:",
        "ab_rem_p1": "• <strong>Ushapan:</strong> Drink lukewarm water from a copper vessel immediately upon waking up without rinsing your mouth. It destroys all stomach ailments.",
        "ab_rem_p2": "• <strong>How to Drink:</strong> Always drink water while sitting and sip by sip. Drinking water while standing causes knee and joint diseases.",
        "ab_rem_p3": "• <strong>Food & Water:</strong> Drinking water immediately after meals is like poison. Consume water only an hour after your meal.",
        "ab_art_title": "Ayurveda & Health: Cosmic Significance of Water and Walking",
        "ab_art_quote": "\"A healthy body is the greatest wealth.\"",
        "ab_art_p1": "Health is a person's greatest wealth. According to <strong>MAHADEV ASTROLOGER M.A.</strong>, our physical body is made of five elements (Fire, Water, Air, Earth, Space). Balancing the 'Water' element is crucial as our body is approximately 70% water. When water and air are imbalanced, the Tridoshas (Vata, Pitta, Kapha) arise.",
        "ab_art_h1": "Accurate Water Intake Science",
        "ab_art_p2": "Ayurveda clearly states that a person's water requirement depends on their weight. Generally, 33 ml of water is needed per 1 kg of weight. Proper water intake keeps your nadis (nerves) pure, making the effect of 'Naad Yoga' (Sound Healing) faster on the body.",
        "ab_art_h2": "Daily Steps & Walking",
        "ab_art_p3": "Both modern science and ancient Ayurveda confirm that regular walking is like nectar for the heart and digestive system. Walking during Brahma Muhurta provides pure oxygen to the brain, destroying mental stress and negative energy. Based on your Body Mass Index (BMI), you must walk 7,000 to 10,000 steps daily.",
    
        "gd_title": "🔱 Grih Dosh Scanner",
        "gd_desc": "Scientifically test your home's energy based on Vedic Vastu and Cosmic Energy.",
        "gd_q1": "1. How do you feel immediately upon entering your home?",
        "gd_q1_o1": "Peaceful and positive energy",
        "gd_q1_o2": "Normal (nothing special)",
        "gd_q1_o3": "Heaviness, suffocation, or unexplained anger",
        "gd_q2": "2. What is the condition of the North-East corner of your home?",
        "gd_q2_o1": "It is clean and has a worship space (Pooja room)",
        "gd_q2_o2": "Heavy items or furniture are placed there",
        "gd_q2_o3": "A toilet or garbage is located there",
        "gd_q3": "3. What is the current status of wealth and health in your home?",
        "gd_q3_o1": "Excellent health and financial growth",
        "gd_q3_o2": "Money comes but is spent on illnesses",
        "gd_q3_o3": "Continuous financial crisis and severe diseases",
        "gd_q4": "4. Do electronic devices break down frequently without reason?",
        "gd_q4_o1": "No, this doesn't happen",
        "gd_q4_o2": "It happens sometimes",
        "gd_q4_o3": "Yes, it happens very frequently",
        "gd_btn_scan": "SCAN ENERGY ➔",
        "gd_res_title": "Energy Report",
        "gd_alert": "Please answer all questions for an accurate result.",
        "gd_lvl_good": "🔱 Pure & Positive Energy",
        "gd_rem_good": "Excellent! The energy of your home is extremely pure.<br><br><strong>Advice:</strong> Perform daily evening Aarti to maintain this positivity.",
        "gd_lvl_mid": "⚠️ Moderate Energy Flaw",
        "gd_rem_mid": "There is some Vastu Dosh or 'Geopathic Stress' present in your home.<br><br><strong>Advice:</strong> Keep the North-East corner clean and use sea salt for mopping. Read the article below for details.",
        "gd_lvl_bad": "🛑 Severe Negative Flaw",
        "gd_rem_bad": "According to the test, a heavy Vastu flaw is present, causing financial and physical harm.<br><br><strong>Urgent Advice:</strong> Play 'Mahamrityunjay Mantra' daily. Contact MAHADEV ASTROLOGER M.A. for personalized solutions.",
        "gd_vastu_box_title": "✨ Why is Vastu Correction essential?",
        "gd_vastu_box_p1": "When the directions and five elements of a house become imbalanced, it creates 'Geopathic Stress'. This stress directly blocks your financial growth and health.",
        "gd_vastu_box_p2": "\"By simply aligning the energy and directions without any demolition, a house can be turned into a 'Positive Magnet'.\"",
        "gd_btn_book": "BOOK VASTU CONSULTATION ➔",
        "gd_art_title": "Grih Dosh: Science, Cosmic Energy & Vedic Solutions",
        "gd_art_quote": "\"Where energy is balanced, there resides Mahadev.\"",
        "gd_art_p1": "Our home is not just a structure of bricks and stones; it is a living entity. The cosmic energy of the universe flows through our dwelling. When this energy is positive, happiness, peace, and prosperity reside in the house. But when the flow of this energy is obstructed, it is called 'Grih Dosh' in Vedic Astrology.",
        "gd_art_p2": "In this research document by <strong>MAHADEV ASTROLOGER M.A.</strong>, we will understand that Grih Dosh is not merely an ancient belief, but holds deep science behind it.",
        "gd_art_h1": "Scientific Perspective: Geopathic Stress",
        "gd_art_p3": "What modern science calls 'Geopathic Stress' was identified by our ancient sages thousands of years ago as 'Vastu Dosh'. Magnetic and electric waves continuously flow within the earth's womb. When a house is constructed against these natural magnetic lines, a kind of stress is generated inside.",
        "gd_art_li1_1": "<strong>Frequency Imbalance:</strong> The human body functions optimally at 7.83 Hz (Schumann Resonance). In a house with negative energy, this frequency gets disrupted, causing unexplained fatigue and anger.",
        "gd_art_li1_2": "<strong>Impact on Electronics:</strong> Where negative ionic charge is high, electronic devices frequently malfunction.",
        "gd_art_h2": "Main Symptoms of Negative Energy",
        "gd_art_p4": "It is essential to understand Mahadev's signs. If you have Grih Dosh, you may experience:",
        "gd_art_li2_1": "<strong>Health Loss:</strong> Continuous illness of family members and medicines having no effect.",
        "gd_art_li2_2": "<strong>Financial Blockage:</strong> Stoppage of wealth inflow or inability to accumulate wealth.",
        "gd_art_li2_3": "<strong>Mental Unrest:</strong> Feeling heaviness and suffocation immediately upon entering.",
        "gd_art_li2_4": "<strong>Insomnia:</strong> Having bad dreams at night and incomplete sleep.",
        "gd_art_highlight": "<strong>Shiva Sutra:</strong> From a place where there is constant discord, both Lakshmi and Narayan depart. Energy purification is the only way.",
        "gd_art_h3": "Science of Directions and Shiva-Shakti Energy",
        "gd_art_p5": "According to Vedic Vastu Shastra, each direction of the house controls a specific form of cosmic energy.",
        "gd_art_li3_1": "<strong>North-East (Ishan):</strong> This is the water element and the place of Dev Guru Jupiter. Mahadev resides here. Impurity in this direction is the biggest Grih Dosh.",
        "gd_art_li3_2": "<strong>South-East (Agneya):</strong> Place of the fire element. Imbalance here causes disease and wealth loss.",
        "gd_art_li3_3": "<strong>South-West (Nairutya):</strong> The earth element. Flaws here cause instability and accidents in life.",
        "gd_art_h4": "Infallible Vedic Solutions (Remedies)",
        "gd_art_p6": "If you have found a flaw through our <strong>Grih Dosh Scanner</strong>, do not despair. By Mahadev's grace, there is a solution to every problem:",
        "gd_art_sh1": "1. Use of Sound Energy (Healing)",
        "gd_art_p7": "Acoustic waves of mantras are the most powerful method to destroy negative energy. Listen to 'Rudrashtakam' or 'Mahamrityunjay Mantra' at home during morning and evening. The sound of a conch shell (Shankh) and bell purifies the atmosphere.",
        "gd_art_sh2": "2. Science of Sea Salt",
        "gd_art_p8": "Sea salt has a wonderful ability to absorb negative ions. Always mix a little sea salt in the water while mopping the floor.",
        "gd_art_sh3": "3. Fire of Camphor and Clove",
        "gd_art_p9": "The chemical reaction that occurs when camphor burns purifies the air. Light camphor and cloves every evening and move it throughout the house.",
        "gd_art_sh4": "4. Installation of Rudraksha",
        "gd_art_p10": "Installing a five-faced (Panchmukhi) Rudraksha at the main door acts as an energy shield, preventing external negative energy from entering the house.",
    
        "k_title": "Free Janam Kundli | MAHADEV ASTROLOGER MA",
        "k_main_heading": "🔱 Janam Kundli (Kundli Engine)",
        "k_sub_heading": "Discover your Moon sign, Nakshatra, and Mangal Dosha based on precise cosmic calculations.",
        "k_dob_lbl": "1. Date of Birth",
        "k_time_lbl": "2. Time of Birth",
        "k_lat_lbl": "3. Latitude",
        "k_lon_lbl": "4. Longitude",
        "k_btn": "Generate Kundli ➔",
        "k_res_title": "Cosmic Blueprint Result",
        "k_art_title": "Importance of Vedic Kundli",
        "k_art_quote": "\"Planetary movements securely guide our cosmic journey.\"",
        "k_art_p1": "Human life is continuously influenced by cosmic energy and planetary movements. A Janam Kundli (Birth Chart) is a precise map of the celestial sphere at the exact time of an individual's birth. Through the advanced 'Astro Engine' of <strong>MAHADEV ASTROLOGER MA</strong>, you can obtain accurate calculations of your life's core elements.",
        "k_art_p2": "This cosmic blueprint provides a proper guide for your career, health, and marital life, helping you align your actions with the universe.",
        "k_faq_h1": "Frequently Asked Questions",
        "k_faq_q1": "1. Is this Kundli calculation highly accurate?",
        "k_faq_a1": "Yes. <b>MAHADEV ASTROLOGER MA</b> utilizes an advanced API server that calculates planetary positions based on absolute astrological mathematics.",
        "k_faq_q2": "2. Does this tool detect Mangal Dosha?",
        "k_faq_a2": "Absolutely. Our system provides a clear indication of Mangal Dosha, helping you in marriage matchmaking and future planning.",
        "k_faq_q3": "3. How do I take an appointment for detailed Kundli analysis (Premium Consultation)?",
        "k_faq_a3": "To get a deep analysis of your horoscope and get accurate solutions, click on the 'Book Premium Consultation' button above. This will take you to our main form page, where you can send us your details by choosing a secure contact option (WhatsApp, Telegram, or Email) according to your convenience."
        "k_art_alert": "<strong>Special Consultation:</strong> Contact <strong>MAHADEV ASTROLOGER MA</strong> for a full horoscope analysis and precise remedies.",
        "k_premium_title": "🔱 Premium Kundli & PDF Report",
        "k_premium_desc": "For complete information on Dasha, Transit results, Kaal Sarp/Manglik Dosh and accurate remedies, consult our experts. See what you get in your Premium PDF:",
        "k_feat_1": "<b>12+ Advanced Charts:</b> D1 (Lagna), Navamsha (D9), Dashamsha (D10), Saptamsha (D7), Chalit, Chandra, Hora & more.",
        "k_feat_2": "<b>Deep Calculations:</b> Avkadha Chakra, Planet Positions, Vimshottari Dasha, and Yogini Dasha charts.",
        "k_feat_3": "<b>Prediction Page:</b> Detailed life predictions with personalized Vedic remedies.",
        "k_feat_4": "<b>Custom Action Links:</b> Direct links tailored strictly to your cosmic needs and ongoing doshas.",
        "k_btn_pdf": "📥 Download PDF for Client",
        "k_loading": "⏳ Loading...",
        "k_planets_title": "Planetary Positions",
        "k_th_planet": "Planet",
        "k_th_rasi": "Rasi",
        "k_th_degree": "Degree",
        "k_th_nak": "Nakshatra",
        "k_th_pada": "Pada",
        "k_th_status": "Status",
        "k_birth_details_title": "Birth Details",
        "k_faq_title": "Frequently Asked Questions (FAQs)",
        "k_premium_btn": "📝 Book Premium Consultation",
    
        "ln_title": "🔱 Advanced Numerology",
        "ln_desc": "Know your Moolank, Bhagyank, Friendly/Enemy Numbers, and Cosmic Beej Mantra.",
        "ln_q1": "1. Your Full Name",
        "ln_q2": "2. Date of Birth",
        "ln_btn": "GENERATE REPORT ➔",
        "ln_res_title": "Cosmic Energy Report",
        "ln_moolank": "Moolank",
        "ln_bhagyank": "Bhagyank",
        "ln_namank": "Namank",
        "ln_lucky_lbl": "✅ Lucky Numbers",
        "ln_avoid_lbl": "❌ Avoid Numbers",
        "ln_lord_lbl": "🔱 Lord Planet: ",
        "ln_color_lbl": "Lucky Color:",
        "ln_day_lbl": "Lucky Day:",
        "ln_mantra_lbl": "📿 Cosmic Beej Mantra:",
        "ln_art_title": "Numerology: Friendly, Enemy Numbers & Navgraha Mantras",
        "ln_art_quote": "\"Every number represents a planet, and every planet is controlled by a mantra.\"",
        "ln_art_p1": "Certain dates or mobile numbers prove to be very lucky for us, while some always cause harm. The reason is the cosmic science of Friendly and Enemy Numbers. According to <strong>MAHADEV ASTROLOGER M.A.</strong>, always choose your 'Lucky Numbers' when starting a new venture or buying a vehicle.",
        "ln_art_h1": "Lords of Numbers 1 to 9 and Vedic Beej Mantras",
        "ln_art_p2": "If your Moolank or Bhagyank is weak, chanting the Beej Mantra of your number's Lord Planet 108 times daily is the most infallible remedy. Here are the proven mantras:",
        "ln_art_c1": "Number 1 (Sun)",
        "ln_art_c2": "Number 2 (Moon)",
        "ln_art_c3": "Number 3 (Jupiter)",
        "ln_art_c4": "Number 4 (Rahu)",
        "ln_art_c5": "Number 5 (Mercury)",
        "ln_art_c6": "Number 6 (Venus)",
        "ln_art_c7": "Number 7 (Ketu)",
        "ln_art_c8": "Number 8 (Saturn)",
        "ln_art_c9": "Number 9 (Mars)",
        "ln_art_alert": "<strong>Special Consultation:</strong> Get your personalized Numerology Report from <strong>MAHADEV ASTROLOGER MA</strong> for Name Correction and detailed number analysis."
    },
    hi: {
        "guide_title": "नवीनतम दिव्य मार्गदर्शन",
        "guide_subtitle": "आधुनिक जीवन के लिए प्राचीन ज्ञान",
        "btn_view_more": "और मार्गदर्शन देखें 🔱",
    
        "ab_title": "🔱 आयुष्मान भव:",
        "ab_desc": "आयुर्वेद और नाद विज्ञान के अनुसार अपनी शारीरिक प्रकृति, दैनिक जल (Water) और ऊर्जा (Steps) का सटीक मापन करें।",
        "ab_q1": "1. आपकी ऊंचाई / Height (cm में)",
        "ab_q2": "2. आपका भार / Weight (kg में)",
        "ab_btn": "स्वास्थ्य जाँच ➔",
        "ab_res_title": "आपकी दैनिक आवश्यकता",
        "ab_lbl_water": "जल (Water)",
        "ab_lbl_steps": "पद-यात्रा",
        "ab_lbl_bmi": "शारीरिक सूचकांक",
        "ab_rem_title": "🌿 वैदिक दिनचर्या सूत्र:",
        "ab_rem_p1": "• <strong>उषापान:</strong> प्रातःकाल उठते ही बिना कुल्ला किए तांबे के पात्र का गुनगुना जल ग्रहण करें। यह उदर (पेट) के सभी रोगों का नाश करता है।",
        "ab_rem_p2": "• <strong>जल ग्रहण विधि:</strong> जल सदैव बैठकर और घूंट-घूंट (Sip by Sip) पिएं। खड़े होकर जल पीने से घुटनों और जोड़ों के रोग उत्पन्न होते हैं।",
        "ab_rem_p3": "• <strong>भोजन और जल:</strong> भोजन के तुरंत पश्चात जल ग्रहण करना विष (Poison) के समान है। भोजन के एक घंटे पश्चात ही जल ग्रहण करें।",
        "ab_art_title": "आयुर्वेद और स्वास्थ्य: जल एवं पद-यात्रा का ब्रह्मांडीय महत्व",
        "ab_art_quote": "\"पहला सुख निरोगी काया।\"",
        "ab_art_p1": "स्वास्थ्य ही मनुष्य का सबसे बड़ा धन है। <strong>MAHADEV ASTROLOGER M.A.</strong> के अनुसार, हमारा भौतिक शरीर पंच तत्वों (अग्नि, जल, वायु, पृथ्वी, आकाश) से निर्मित है। इन सभी में 'जल' तत्व का संतुलन अत्यंत आवश्यक है क्योंकि हमारे शरीर का लगभग 70 प्रतिशत भाग जल ही है। जब हमारे शरीर में जल और वायु का संतुलन बिगड़ता है, तब त्रिदोष (वात, पित्त, कफ) उत्पन्न होते हैं।",
        "ab_art_h1": "सटीक जल पान (Water Intake Science)",
        "ab_art_p2": "आयुर्वेद का स्पष्ट निर्देश है कि प्रत्येक व्यक्ति की जल की आवश्यकता उसके भार (Weight) पर निर्भर करती है। सामान्य रूप से, प्रत्येक 1 किलोग्राम भार के लिए 33 मिली-लीटर जल की आवश्यकता होती है। यदि आप उचित मात्रा में जल ग्रहण करते हैं, तो आपकी नाड़ियाँ शुद्ध रहती हैं और 'नाद योग' (Sound Healing) का प्रभाव शरीर पर शीघ्र होता है।",
        "ab_art_h2": "दैनिक पद-यात्रा (Daily Steps & Walking)",
        "ab_art_p3": "आधुनिक विज्ञान और प्राचीन आयुर्वेद दोनों यह प्रमाणित करते हैं कि नियमित पद-यात्रा (चलना) हृदय और पाचन तंत्र के लिए अमृत के समान है। ब्रह्म मुहूर्त में की गई पद-यात्रा से मस्तिष्क को शुद्ध प्राणवायु (Oxygen) प्राप्त होती है, जिससे मानसिक तनाव और नकारात्मक ऊर्जा का नाश होता है। अपने शारीरिक सूचकांक (BMI) के आधार पर 7,000 से 10,000 कदम प्रतिदिन अवश्य चलना चाहिए।",
   
        "gd_title": "🔱 गृह दोष स्कैनर",
        "gd_desc": "वैदिक वास्तु और ब्रह्मांडीय ऊर्जा (Cosmic Energy) के आधार पर अपने घर का वैज्ञानिक परीक्षण करें।",
        "gd_q1": "1. घर में प्रवेश करते ही आपको कैसा अनुभव होता है?",
        "gd_q1_o1": "शांति और सकारात्मक ऊर्जा",
        "gd_q1_o2": "सामान्य (कुछ विशेष नहीं)",
        "gd_q1_o3": "भारीपन, घुटन या अकारण क्रोध",
        "gd_q2": "2. घर के ईशान कोण (North-East) की स्थिति क्या है?",
        "gd_q2_o1": "स्वच्छ है और वहां पूजा स्थान है",
        "gd_q2_o2": "वहां भारी सामान रखा है",
        "gd_q2_o3": "वहां शौचालय (Toilet) या कूड़ा है",
        "gd_q3": "3. धन और स्वास्थ्य की वर्तमान स्थिति कैसी है?",
        "gd_q3_o1": "उत्तम स्वास्थ्य और आर्थिक वृद्धि",
        "gd_q3_o2": "धन आता है परंतु रोग में व्यय होता है",
        "gd_q3_o3": "निरंतर आर्थिक संकट और गंभीर रोग",
        "gd_q4": "4. क्या घर में इलेक्ट्रॉनिक उपकरण अकारण खराब होते हैं?",
        "gd_q4_o1": "नहीं, ऐसा नहीं होता",
        "gd_q4_o2": "कभी-कभी होता है",
        "gd_q4_o3": "हाँ, बहुत अधिक होता है",
        "gd_btn_scan": "SCAN ENERGY ➔",
        "gd_res_title": "Energy Report",
        "gd_alert": "सटीक परिणाम हेतु कृपया सभी प्रश्नों के उत्तर दें।",
        "gd_lvl_good": "🔱 शुद्ध एवं सकारात्मक ऊर्जा",
        "gd_rem_good": "अति उत्तम! आपके घर की ऊर्जा अत्यंत शुद्ध है।<br><br><strong>परामर्श:</strong> इस सकारात्मकता को बनाए रखने के लिए नित्य संध्या आरती करें।",
        "gd_lvl_mid": "⚠️ मध्यम ऊर्जा दोष",
        "gd_rem_mid": "आपके घर में कुछ वास्तु दोष या 'Geopathic Stress' उपस्थित है।<br><br><strong>परामर्श:</strong> ईशान कोण (North-East) को स्वच्छ रखें और समुद्री नमक का प्रयोग करें। विस्तृत जानकारी नीचे दिए गए लेख में पढ़ें।",
        "gd_lvl_bad": "🛑 तीव्र नकारात्मक दोष",
        "gd_rem_bad": "परीक्षण के अनुसार घर में भारी वास्तु दोष उपस्थित है, जो आर्थिक एवं शारीरिक हानि का कारण है।<br><br><strong>तत्काल परामर्श:</strong> घर में नित्य 'महामृत्युंजय मंत्र' चलाएं। व्यक्तिगत समाधान हेतु <strong>MAHADEV ASTROLOGER M.A.</strong> से संपर्क करें।",
        "gd_vastu_box_title": "✨ Vastu Correction (वास्तु उपाय) क्यों ज़रूरी है?",
        "gd_vastu_box_p1": "जब घर की दिशाएं और पंचतत्व असंतुलित हो जाते हैं, तो इसे <strong>'Geopathic Stress'</strong> कहा जाता है। यह तनाव सीधे आपकी आर्थिक वृद्धि और स्वास्थ्य को अवरुद्ध करता है।",
        "gd_vastu_box_p2": "\"बिना तोड़-फोड़ के केवल ऊर्जा (Energy) और दिशाओं को अलाइन करके घर को एक 'सकारात्मक चुंबक' (Positive Magnet) बनाया जा सकता है।\"",
        "gd_btn_book": "वास्तु परामर्श बुक करें ➔",
        "gd_art_title": "गृह दोष: विज्ञान, ब्रह्मांडीय ऊर्जा और वैदिक समाधान",
        "gd_art_quote": "\"जहाँ ऊर्जा का संतुलन है, वहीं महादेव का वास है।\"",
        "gd_art_p1": "हमारा घर केवल ईंट और पत्थर का ढांचा नहीं है; यह एक जीवंत इकाई (Living Entity) है। ब्रह्मांड की समस्त ऊर्जा हमारे निवास स्थान से होकर गुजरती है। जब यह ऊर्जा सकारात्मक होती है, तो घर में सुख, शांति और समृद्धि का वास होता है। परंतु जब इस ऊर्जा का प्रवाह बाधित होता है, तो उसे वैदिक ज्योतिष में <strong>'गृह दोष' (Grih Dosh)</strong> कहा जाता है।",
        "gd_art_p2": "<strong>MAHADEV ASTROLOGER M.A.</strong> के इस शोध पत्र में हम यह समझेंगे कि गृह दोष केवल एक प्राचीन मान्यता नहीं है, बल्कि इसके पीछे गहरा विज्ञान (Science) छिपा है।",
        "gd_art_h1": "वैज्ञानिक दृष्टिकोण: जियोपैथिक स्ट्रेस (Geopathic Stress)",
        "gd_art_p3": "आधुनिक विज्ञान जिसे 'Geopathic Stress' कहता है, हमारे प्राचीन ऋषियों ने उसे सहस्रों वर्ष पूर्व 'वास्तु दोष' के रूप में पहचान लिया था। पृथ्वी के गर्भ में निरंतर चुंबकीय (Magnetic) और विद्युतीय (Electric) तरंगें बहती रहती हैं। जब घर का निर्माण पृथ्वी की इन प्राकृतिक चुंबकीय रेखाओं के विरुद्ध किया जाता है, तो घर के भीतर एक प्रकार का तनाव उत्पन्न होता है।",
        "gd_art_li1_1": "<strong>फ्रीक्वेंसी का असंतुलन:</strong> मानव शरीर 7.83 Hz (Schumann Resonance) पर सर्वोत्तम कार्य करता है। नकारात्मक ऊर्जा वाले घर में यह फ्रीक्वेंसी बिगड़ जाती है, जिससे अकारण थकान और क्रोध उत्पन्न होता है।",
        "gd_art_li1_2": "<strong>इलेक्ट्रॉनिक्स पर प्रभाव:</strong> जहाँ नकारात्मक ऊर्जा (Negative Ionic Charge) अधिक होती है, वहाँ इलेक्ट्रॉनिक उपकरण बार-बार खराब होते हैं।",
        "gd_art_h2": "घर में नकारात्मक ऊर्जा के मुख्य लक्षण",
        "gd_art_p4": "महादेव के संकेतों को समझना आवश्यक है। यदि आपके घर में गृह दोष है, तो आपको निम्नलिखित लक्षण अनुभव हो सकते हैं:",
        "gd_art_li2_1": "<strong>स्वास्थ्य हानि:</strong> घर के सदस्यों का निरंतर अस्वस्थ रहना और औषधियों का प्रभाव न होना।",
        "gd_art_li2_2": "<strong>आर्थिक अवरोध:</strong> धन का आगमन रुक जाना या धन संचय न हो पाना।",
        "gd_art_li2_3": "<strong>मानसिक अशांति:</strong> घर में प्रवेश करते ही भारीपन और घुटन का अनुभव होना।",
        "gd_art_li2_4": "<strong>अनिद्रा (Insomnia):</strong> रात्रि में बुरे स्वप्न आना और नींद पूर्ण न होना।",
        "gd_art_highlight": "<strong>शिव सूत्र:</strong> जिस स्थान पर निरंतर कलह होता है, वहाँ से लक्ष्मी और नारायण दोनों प्रस्थान कर जाते हैं। ऊर्जा का शुद्धिकरण ही एकमात्र मार्ग है।",
        "gd_art_h3": "दिशाओं का विज्ञान और शिव-शक्ति ऊर्जा",
        "gd_art_p5": "वैदिक वास्तु शास्त्र के अनुसार, घर की प्रत्येक दिशा ब्रह्मांडीय ऊर्जा के एक विशिष्ट रूप को नियंत्रित करती है।",
        "gd_art_li3_1": "<strong>ईशान कोण (North-East):</strong> यह जल तत्व और देव गुरु बृहस्पति का स्थान है। यहाँ महादेव का वास माना जाता है। इस दिशा का अशुद्ध होना सबसे बड़ा गृह दोष है।",
        "gd_art_li3_2": "<strong>आग्नेय कोण (South-East):</strong> यह अग्नि तत्व का स्थान है। यहाँ असंतुलन होने पर घर में रोग और धन हानि होती है।",
        "gd_art_li3_3": "<strong>नैऋत्य कोण (South-West):</strong> यह पृथ्वी तत्व है। यहाँ का दोष जीवन में अस्थिरता और दुर्घटनाओं का कारण बनता है।",
        "gd_art_h4": "अचूक वैदिक समाधान (Vedic Remedies)",
        "gd_art_p6": "यदि आपने हमारे <strong>Grih Dosh Scanner</strong> के माध्यम से घर में दोष पाया है, तो निराश न हों। महादेव की कृपा से हर समस्या का समाधान उपलब्ध है:",
        "gd_art_sh1": "1. ध्वनि ऊर्जा (Sound Healing) का प्रयोग",
        "gd_art_p7": "मंत्रों की ध्वनि तरंगें (Acoustic Waves) नकारात्मक ऊर्जा को नष्ट करने की सबसे शक्तिशाली विधि हैं। प्रातः और संध्या के समय घर में 'रुद्राष्टकम' या 'महामृत्युंजय मंत्र' का श्रवण करें। शंख और घंटी की ध्वनि घर के वायुमंडल को शुद्ध करती है।",
        "gd_art_sh2": "2. समुद्री नमक (Sea Salt) का विज्ञान",
        "gd_art_p8": "समुद्री नमक में नकारात्मक आयनों (Negative Ions) को सोखने की अद्भुत क्षमता होती है। घर में पोंछा लगाते समय जल में थोड़ा सा समुद्री नमक अवश्य मिलाएं।",
        "gd_art_sh3": "3. कर्पूर और लौंग की अग्नि",
        "gd_art_p9": "कर्पूर (Camphor) जलने पर जो रासायनिक प्रतिक्रिया (Chemical Reaction) होती है, वह वायु को शुद्ध करती है। नित्य संध्याकाल में कर्पूर और लौंग प्रज्वलित कर पूरे घर में घुमाएं।",
        "gd_art_sh4": "4. रुद्राक्ष की स्थापना",
        "gd_art_p10": "पंचमुखी रुद्राक्ष को घर के मुख्य द्वार पर स्थापित करने से यह एक सुरक्षा कवच (Energy Shield) का कार्य करता है, जो बाहरी नकारात्मक ऊर्जा को घर में प्रवेश करने से रोकता है。",
    
        "k_title": "फ्री जन्म कुण्डली | MAHADEV ASTROLOGER MA",
        "k_main_heading": "🔱 जन्म कुण्डली (Kundli Engine)",
        "k_sub_heading": "सटीक ब्रह्मांडीय गणनाओं के आधार पर अपना राशिफल, नक्षत्र और मंगल दोष जानें।",
        "k_dob_lbl": "1. जन्म तिथि (Date of Birth)",
        "k_time_lbl": "2. जन्म समय (Time of Birth)",
        "k_lat_lbl": "3. अक्षांश (Latitude)",
        "k_lon_lbl": "4. देशांतर (Longitude)",
        "k_btn": "कुण्डली बनाएं ➔",
        "k_res_title": "ब्रह्मांडीय ऊर्जा परिणाम",
        "k_art_title": "वैदिक कुण्डली का महत्व",
        "k_art_quote": "\"ग्रहों की गति हमारे जीवन का मार्गदर्शन करती है।\"",
        "k_art_p1": "मानव जीवन ब्रह्मांडीय ऊर्जा (Cosmic Energy) और ग्रहों की गति से निरंतर प्रभावित होता है। जन्म कुण्डली व्यक्ति के जन्म के समय आकाश मंडल का एक सटीक नक्शा है। <strong>MAHADEV ASTROLOGER MA</strong> के इस उन्नत 'Astro Engine' के माध्यम से आप अपने जीवन के मूल तत्वों की सटीक गणना प्राप्त कर सकते हैं।",
        "k_art_p2": "यह ब्रह्मांडीय ब्लूप्रिंट आपके करियर, स्वास्थ्य और दांपत्य जीवन के लिए उचित मार्गदर्शिका प्रदान करता है, जिससे आप अपने कर्मों को ब्रह्मांड के अनुकूल बना सकते हैं।",
        "k_faq_h1": "सामान्य प्रश्न (FAQ)",
        "k_faq_q1": "1. क्या यह कुण्डली गणना पूर्णतः सटीक है?",
        "k_faq_a1": "हाँ। <b>MAHADEV ASTROLOGER MA</b> एक उन्नत API सर्वर का उपयोग करता है जो पूर्ण ज्योतिषीय गणित के आधार पर ग्रहों की स्थिति की गणना करता है।",
        "k_faq_q2": "2. क्या यह उपकरण मंगल दोष का संकेत देता है?",
        "k_faq_a2": "अवश्य। हमारा सिस्टम मंगल दोष का स्पष्ट संकेत प्रदान करता है, जो विवाह मिलान और भविष्य की योजना में आपकी सहायता करता है।",
        "k_faq_q3": "3. विस्तृत कुण्डली विश्लेषण (प्रीमियम परामर्श) के लिए अपॉइंटमेंट कैसे लें?",
        "k_faq_a3": "अपनी कुण्डली का गहन विश्लेषण और सटीक उपाय प्राप्त करने के लिए ऊपर दिए गए 'Book Premium Consultation' बटन पर क्लिक करें। यह आपको हमारे मुख्य फॉर्म पेज पर ले जाएगा, जहाँ आप अपनी सुविधा के अनुसार सुरक्षित संपर्क विकल्प (WhatsApp, Telegram, या Email) चुनकर हमें अपनी डिटेल्स भेज सकते हैं।"
        "k_art_alert": "<strong>विशेष परामर्श:</strong> संपूर्ण कुण्डली विश्लेषण और सटीक उपाय जानने के लिए <strong>MAHADEV ASTROLOGER MA</strong> से संपर्क करें।",
        "k_premium_title": "🔱 प्रीमियम कुण्डली और PDF रिपोर्ट",
        "k_premium_desc": "महादशा, गोचर फल, काल सर्प/मांगलिक दोष और सटीक उपायों की पूरी जानकारी के लिए हमारे विशेषज्ञों से परामर्श लें। आपकी प्रीमियम PDF में आपको यह सब मिलेगा:",
        "k_feat_1": "<b>12+ एडवांस चार्ट्स:</b> D1 (लग्न), नवमांश (D9), दशमांश (D10), सप्तमांश (D7), चलित, चंद्र, होरा और अन्य महत्वपूर्ण चार्ट।",
        "k_feat_2": "<b>सटीक गणनाएं:</b> अवखड़ा चक्र, ग्रहों की स्थिति, विंशोत्तरी दशा और योगिनी दशा चार्ट।",
        "k_feat_3": "<b>प्रेडिक्शन पेज:</b> आपके जीवन की विस्तृत भविष्यवाणी और व्यक्तिगत वैदिक उपाय।",
        "k_feat_4": "<b>कस्टम एक्शन लिंक्स:</b> आपकी ग्रहीय आवश्यकता और दोषों के अनुसार काम आने वाले महत्वपूर्ण डायरेक्ट लिंक्स।",
        "k_btn_pdf": "📥 क्लाइंट के लिए PDF डाउनलोड करें",
        "k_loading": "⏳ कृपया प्रतीक्षा करें...",
        "k_planets_title": "ग्रहों की स्थिति (Planetary Positions)",
        "k_th_planet": "ग्रह",
        "k_th_rasi": "राशि",
        "k_th_degree": "अंश (Degree)",
        "k_th_nak": "नक्षत्र",
        "k_th_pada": "पद",
        "k_th_status": "स्थिति",
        "k_birth_details_title": "जन्म विवरण",
        "k_faq_title": "सामान्य प्रश्न (FAQs)",
        "k_premium_btn": "📝 प्रीमियम परामर्श बुक करें",
  
        "ln_title": "🔱 अंक ज्योतिष कैलकुलेटर",
        "ln_desc": "अपना मूलांक, भाग्यांक, शुभ/अशुभ अंक (Friendly & Enemy Numbers) और बीज मंत्र जानें।",
        "ln_q1": "1. आपका पूरा नाम (Full Name)",
        "ln_q2": "2. जन्म तिथि (Date of Birth)",
        "ln_btn": "अंक जानें ➔",
        "ln_res_title": "ब्रह्मांडीय ऊर्जा रिपोर्ट",
        "ln_moolank": "मूलांक",
        "ln_bhagyank": "भाग्यांक",
        "ln_namank": "नामांक",
        "ln_lucky_lbl": "✅ शुभ अंक (Lucky Numbers)",
        "ln_avoid_lbl": "❌ शत्रु अंक (Avoid Numbers)",
        "ln_lord_lbl": "🔱 स्वामी ग्रह: ",
        "ln_color_lbl": "शुभ रंग:",
        "ln_day_lbl": "शुभ दिन:",
        "ln_mantra_lbl": "📿 सिद्ध बीज मंत्र:",
        "ln_art_title": "अंक ज्योतिष: मित्र, शत्रु अंक और नवग्रह मंत्र",
        "ln_art_quote": "\"प्रत्येक अंक एक ग्रह का प्रतिनिधित्व करता है, और प्रत्येक ग्रह एक मंत्र से नियंत्रित होता है।\"",
        "ln_art_p1": "हमारे जीवन में कुछ तारीखें या मोबाइल नंबर हमारे लिए बहुत भाग्यशाली (Lucky) साबित होते हैं, जबकि कुछ नंबर हमें हमेशा नुकसान पहुँचाते हैं। इसका कारण है मित्र और शत्रु अंकों का ब्रह्मांडीय विज्ञान। <strong>MAHADEV ASTROLOGER M.A.</strong> के अनुसार, यदि आप कोई नया कार्य आरंभ कर रहे हैं, तो हमेशा अपने 'शुभ अंकों' का ही चयन करें।",
        "ln_art_h1": "1 से 9 अंकों के स्वामी ग्रह और उनके वैदिक बीज मंत्र",
        "ln_art_p2": "यदि आपका मूलांक या भाग्यांक कमज़ोर है, तो अपने अंक के स्वामी ग्रह (Lord Planet) के <strong>बीज मंत्र</strong> का नित्य 108 बार जाप करना सबसे अचूक उपाय है। यहाँ 1 से 9 अंकों के स्वामी और उनके सिद्ध मंत्र दिए गए हैं:",
        "ln_art_c1": "अंक 1 (सूर्य)",
        "ln_art_c2": "अंक 2 (चंद्रमा)",
        "ln_art_c3": "अंक 3 (गुरु)",
        "ln_art_c4": "अंक 4 (राहु)",
        "ln_art_c5": "अंक 5 (बुध)",
        "ln_art_c6": "अंक 6 (शुक्र)",
        "ln_art_c7": "अंक 7 (केतु)",
        "ln_art_c8": "अंक 8 (शनि)",
        "ln_art_c9": "अंक 9 (मंगल)",
        "ln_art_alert": "<strong>विशेष परामर्श:</strong> नाम की स्पेलिंग (Name Correction) और अंकों के महा-विश्लेषण के लिए <strong>MAHADEV ASTROLOGER MA</strong> से अपनी व्यक्तिगत न्यूमरोलॉजी रिपोर्ट प्राप्त करें।"
    }
};
