window.pageTranslations = {
    en: {
        "gem_title": "Certified Gemstones | Astrological Remedies",
        "gem_intro_h1": "Source of Cosmic Energy: Navratna",
        "gem_intro_p1": "Gemstones hold a highly significant place in Astrology. They are not merely ornaments, but act as receivers that absorb cosmic rays and planetary energies. <strong>MAHADEV ASTROLOGER MA</strong> provides you with completely pure, natural, and lab-certified gemstones.",
        "gem_intro_p2": "Wearing the appropriate gemstone according to your birth chart reduces the effect of negative planets, balances the chakras, and infuses positive energy, happiness, and peace into your life.",
        
        "ratna_ruby": "Ruby (Manikya)",
        "desc_ruby": "<strong>Ruling Planet: Sun</strong><br>Wearing Ruby enhances self-confidence, leadership qualities, and prestige. It is helpful in maintaining excellent health and energy.",
        "ratna_pearl": "Pearl (Moti)",
        "desc_pearl": "<strong>Ruling Planet: Moon</strong><br>Pearl provides peace to the mind and removes mental stress. It is the best gemstone for balancing emotions.",
        "ratna_coral": "Red Coral (Moonga)",
        "desc_coral": "<strong>Ruling Planet: Mars</strong><br>Coral increases courage, energy, and physical strength. It is highly beneficial in resolving land and debt-related issues.",
        "ratna_emerald": "Emerald (Panna)",
        "desc_emerald": "<strong>Ruling Planet: Mercury</strong><br>Emerald is the significator of intellect, memory, and success in business. It is worn to sharpen speech and communication skills.",
        "ratna_pukhraj": "Yellow Sapphire (Pukhraj)",
        "desc_pukhraj": "<strong>Ruling Planet: Jupiter</strong><br>Yellow Sapphire is a symbol of knowledge, good fortune, and marital bliss. It opens the doors to financial prosperity and spiritual progress.",
        "ratna_diamond": "Diamond / Opal",
        "desc_diamond": "<strong>Ruling Planet: Venus</strong><br>This gemstone grants beauty, attraction, material comforts, and success in the field of arts. Best for obtaining the grace of Venus.",
        "ratna_neelam": "Blue Sapphire (Neelam)",
        "desc_neelam": "<strong>Ruling Planet: Saturn</strong><br>Blue Sapphire is an extremely intense and powerful gemstone. It provides discipline, justice, and rapid success in the workspace.",
        "ratna_gomed": "Hessonite (Gomed)",
        "desc_gomed": "<strong>Ruling Planet: Rahu</strong><br>Hessonite is worn to pacify the ill effects of Rahu and to overcome sudden obstacles.",
        
        "btn_enquire": "Enquire Now",
        
        "wear_title": "The Proper Vedic Method of Wearing Gemstones",
        "wear_desc": "The full benefit of gemstones is achieved only when they are worn in the correct metal, the correct finger, and at an auspicious time.",
        "method_1_title": "1. Astrological Consultation",
        "method_1_desc": "One should never wear any gemstone without a horoscope analysis. Choose a favorable gemstone only according to your birth chart.",
        "method_2_title": "2. Choosing the Metal",
        "method_2_desc": "Each gemstone has a specific metal. For example, Yellow Sapphire is most effective in Gold, and Pearl in Silver.",
        "method_3_title": "3. Energization (Pran Pratishtha)",
        "method_3_desc": "Before wearing, it is mandatory to purify the gemstone with Panchamrit and energize it with the Vedic mantras of its respective planet.",
        
        "faq_title": "Frequently Asked Questions About Gemstones",
        "faq_q1": "Are all your gemstones Lab Certified?",
        "faq_a1": "Yes, absolutely. We do not compromise on authenticity. The original certificate from a reputed laboratory is provided to you along with the gemstone.",
        "faq_q2": "Do you send the gemstone studded in a Ring?",
        "faq_a2": "Yes, upon special request and according to the customer's ring size, we get the gemstone studded in Gold, Silver, or Ashtadhatu, and send it fully energized.",
        "faq_q3": "When does a gemstone start showing its effect?",
        "faq_a3": "The effect of a gemstone depends on its type. Gemstones like Blue Sapphire show very quick results, while other gemstones may take 30 to 45 days to connect with cosmic energy."
    },
    hi: {
        "gem_title": "Certified Gemstones | प्रामाणिक ज्योतिषीय रत्न",
        "gem_intro_h1": "ब्रह्मांडीय ऊर्जा का स्रोत: नव रत्न",
        "gem_intro_p1": "ज्योतिष शास्त्र में रत्नों का अत्यंत महत्वपूर्ण स्थान है। रत्न केवल आभूषण नहीं हैं, बल्कि ये ब्रह्मांडीय किरणों (Cosmic Rays) और ग्रहों की ऊर्जा को ग्रहण करने वाले यंत्र के रूप में कार्य करते हैं। <strong>MAHADEV ASTROLOGER MA</strong> आपको पूर्ण रूप से शुद्ध, प्राकृतिक और प्रयोगशाला द्वारा प्रमाणित (Lab Certified) रत्न उपलब्ध कराता है।",
        "gem_intro_p2": "जन्म कुंडली के अनुसार उचित रत्न धारण करने से नकारात्मक ग्रहों का प्रभाव कम होता है, चक्र संतुलित होते हैं, और जीवन में सकारात्मक ऊर्जा (Positive Energy), सुख और शांति का संचार होता है।",
        
        "ratna_ruby": "Ruby (माणिक्य)",
        "desc_ruby": "<strong>स्वामी ग्रह: सूर्य (Sun)</strong><br>माणिक्य धारण करने से आत्मविश्वास, नेतृत्व क्षमता और मान-सम्मान में वृद्धि होती है। यह स्वास्थ्य और ऊर्जा को उत्तम बनाए रखने में सहायक है।",
        "ratna_pearl": "Pearl (मोती)",
        "desc_pearl": "<strong>स्वामी ग्रह: चंद्र (Moon)</strong><br>मोती मन को शांति प्रदान करता है और मानसिक तनाव (Stress) को दूर करता है। यह भावनाओं को संतुलित करने के लिए सर्वोत्तम रत्न है।",
        "ratna_coral": "Red Coral (मूंगा)",
        "desc_coral": "<strong>स्वामी ग्रह: मंगल (Mars)</strong><br>मूंगा साहस, ऊर्जा और शारीरिक बल में वृद्धि करता है। भूमि और ऋण (Debt) संबंधी समस्याओं के समाधान में यह अत्यंत लाभकारी है।",
        "ratna_emerald": "Emerald (पन्ना)",
        "desc_emerald": "<strong>स्वामी ग्रह: बुध (Mercury)</strong><br>पन्ना बुद्धि, स्मरण शक्ति और व्यापार में सफलता का कारक है। वाणी (Speech) और संचार कौशल को प्रखर करने के लिए इसे धारण किया जाता है।",
        "ratna_pukhraj": "Yellow Sapphire (पुखराज)",
        "desc_pukhraj": "<strong>स्वामी ग्रह: गुरु (Jupiter)</strong><br>पुखराज ज्ञान, सौभाग्य, और वैवाहिक सुख का प्रतीक है। यह आर्थिक समृद्धि और आध्यात्मिक उन्नति के द्वार खोलता है।",
        "ratna_diamond": "Diamond / Opal (हीरा/ओपल)",
        "desc_diamond": "<strong>स्वामी ग्रह: शुक्र (Venus)</strong><br>यह रत्न सौंदर्य, आकर्षण, भौतिक सुख और कला के क्षेत्र में सफलता प्रदान करता है। शुक्र की कृपा प्राप्ति के लिए यह सर्वोत्तम है।",
        "ratna_neelam": "Blue Sapphire (नीलम)",
        "desc_neelam": "<strong>स्वामी ग्रह: शनि (Saturn)</strong><br>नीलम एक अत्यंत तीव्र और शक्तिशाली रत्न है। यह अनुशासन, न्याय और कार्यक्षेत्र में तीव्र सफलता (Success) प्रदान करता है।",
        "ratna_gomed": "Hessonite (गोमेद)",
        "desc_gomed": "<strong>स्वामी ग्रह: राहु (Rahu)</strong><br>राहु के दुष्प्रभावों को शांत करने और अचानक आने वाली बाधाओं को दूर करने के लिए गोमेद धारण किया जाता है।",
        
        "btn_enquire": "Enquire Now / पूछताछ करें",
        
        "wear_title": "रत्न धारण करने की उचित वैदिक विधि",
        "wear_desc": "रत्नों का पूर्ण लाभ तभी प्राप्त होता है, जब उन्हें सही धातु (Metal), सही उंगली और शुभ मुहूर्त में धारण किया जाए।",
        "method_1_title": "1. ज्योतिषीय परामर्श (Astrological Consultation)",
        "method_1_desc": "बिना कुंडली विश्लेषण के कभी भी कोई रत्न धारण नहीं करना चाहिए। अपनी जन्म कुंडली के अनुसार ही अनुकूल रत्न का चयन करें।",
        "method_2_title": "2. धातु का चयन (Choosing the Metal)",
        "method_2_desc": "प्रत्येक रत्न की एक विशेष धातु होती है। जैसे पुखराज स्वर्ण (Gold) में और मोती चांदी (Silver) में सर्वाधिक प्रभावशाली होते हैं।",
        "method_3_title": "3. प्राण-प्रतिष्ठा (Energization)",
        "method_3_desc": "धारण करने से पूर्व रत्न को पंचामृत से शुद्ध करके उसके संबंधित ग्रह के वैदिक मंत्रों द्वारा सिद्ध (Energize) करना अनिवार्य है।",
        
        "faq_title": "रत्नों से संबंधित सामान्य प्रश्न (FAQ)",
        "faq_q1": "क्या आपके सभी रत्न प्रयोगशाला द्वारा प्रमाणित (Lab Certified) हैं?",
        "faq_a1": "जी हाँ, पूर्ण रूप से। हम प्रामाणिकता के साथ कोई समझौता नहीं करते। आपको रत्न के साथ प्रतिष्ठित प्रयोगशाला का मूल प्रमाण पत्र (Original Certificate) प्रदान किया जाता है।",
        "faq_q2": "क्या आप रत्न को अंगूठी (Ring) में जड़वा कर भेजते हैं?",
        "faq_a2": "हाँ, ग्राहकों के विशेष अनुरोध और उंगली के माप (Ring Size) के अनुसार, हम रत्न को स्वर्ण, रजत या अष्टधातु में निर्मित करवा कर और उसे सिद्ध (Energize) करके भेजते हैं।",
        "faq_q3": "रत्न अपना प्रभाव दिखाना कब आरंभ करता है?",
        "faq_a3": "रत्न का प्रभाव उसके प्रकार पर निर्भर करता है। नीलम जैसे रत्न अत्यंत शीघ्र प्रभाव दिखाते हैं, जबकि अन्य रत्नों को ब्रह्मांडीय ऊर्जा से जुड़ने में 30 से 45 दिन का समय लग सकता है।"
    }
};
