/**
 * MAHADEV ASTROLOGER MA - Astro Store Products Translation Database
 * Synced Sequence: English Block First, Hindi Block Second (100% Complete)
 */

window.productsTranslation = {
  // =====================================================================
  // 🔱 ENGLISH TRANSLATIONS BLOCK
  // =====================================================================
  en: {
    // --- 1. Main Shop Page ---
    shop_title: "MAHADEV ASTROLOGER STORE",
    shop_subtitle: "100% Authentic Spiritual, Astrological & Herbal Products",
    shop_intro_desc: "The right balance of nature and energy can provide a positive direction to your life. All our products are ritually energized through Vedic mantras so that you receive their complete divine benefits.",
    trust_title: "Our Authenticity",
    fssai_reg_title: "FSSAI Registered",
    fssai_reg_desc: "All our herbal and wellness products are approved by FSSAI, which certifies their utmost purity and safety standards.",
    lab_cert_title: "Lab Certified",
    lab_cert_desc: "All gemstones and Rudrakshas are certified by authorized government-approved laboratories. We strictly prohibit counterfeit products.",
    vedic_energized_title: "Vedic Energized",
    vedic_energized_desc: "Before dispatch, every gemstone and Yantra is ritually energized (Pran Pratishtha) through sacred Vedic mantras according to your specific name and Gotra.",
    divine_store: "Divine Store Categories",
    cat_gemstones: "Gemstones (Ratna)",
    desc_gemstones: "Acquire lab-certified gemstones suitable for your horoscope to mitigate planetary afflictions and attract good fortune.",
    cat_rudraksha: "Sacred Rudraksha",
    desc_rudraksha: "Authentic Nepali and Indonesian Rudrakshas (1 to 14 Mukhi), highly beneficial for meditation, spiritual growth, and health.",
    cat_herbs: "Herbal Wellness",
    desc_herbs: "Natural roots (Jadi) and FSSAI certified medicines that maintain your physical vitality and emotional equilibrium.",
    cat_energy_kits: "Energy Kits & Puja Items",
    desc_energy_kits: "Vastu remedies, divine Yantras, and complete Puja kits designed to channelize positive cosmic vibrations into your home or office.",
    how_to_order_title: "How to Order",
    step_01_label: "01. Select Product:",
    step_01_desc: "Choose the appropriate gemstone, Rudraksha, or herbal root based on your astrological requirements.",
    step_02_label: "02. Contact via WhatsApp:",
    step_02_desc: "Click on the 'Order' button to connect with our Divine Lab directly on WhatsApp.",
    step_03_label: "03. Secure Payment:",
    step_03_desc: "Once the product specification is finalized, make a secure payment via UPI or Bank Transfer.",
    step_04_label: "04. Energization & Delivery:",
    step_04_desc: "After being ritually energized through Vedic rituals, your product will be safely delivered to your doorstep within 3 to 5 business days.",
    shop_faq_title: "Astro Shop FAQs",
    shop_q1: "Are all gemstones and Rudrakshas certified?",
    shop_a1: "Yes, every single item purchased from our store comes with an official, government-approved laboratory certificate detailing its exact weight, dimensions, and authentic properties.",
    shop_q2: "How are the products energized or consecrated?",
    shop_a2: "According to authentic Vedic customs, the products undergo a comprehensive Pran Pratishtha ritual under your specific Name and Gotra using specialized planetary mantras to ensure optimum impact.",
    shop_q3: "How do the herbal wellness products benefit us?",
    shop_a3: "Our herbal wellness selections are rooted in deep astrological research and classical Ayurveda. They are completely FSSAI certified and used as substitute planetary remedies (Jadi) to pacify weak planets naturally.",

    // --- 2. Gemstones Page ---
    gem_title: "Vedic Navgrah Gemstones",
    gem_subtitle: "100% Pure, Certified & Ritually Energized Gemstones",
    gem_intro_desc: "According to Vedic astrology, each planet emits a specific cosmic energy and radiation. When a planet is weak in the horoscope, wearing its respective pure gemstone enhances its divine energy. At MAHADEV ASTROLOGER MA, you will receive only natural, unheated, untreated, and lab-certified gemstones.",
    premium_gems_title: "Premium Navgrah Gemstones",
    gem_pukhraj: "Yellow Sapphire (Pukhraj)",
    desc_pukhraj: "Gemstone for Lord Jupiter (Brihaspati). Highly beneficial for accelerating higher intellect, acquiring wealth, and resolving marital hurdles.",
    gem_neelam: "Blue Sapphire (Neelam)",
    desc_neelam: "Powerful gemstone for Saturn (Shani). Excellent for business expansion, protection from adversaries, and mental stability.",
    gem_manikya: "Natural Ruby (Manikya)",
    desc_manikya: "The gemstone of the Sun (Surya). Ideal for boosting self-confidence, leadership qualities, and attaining success in administrative works.",
    gem_panna: "Natural Emerald (Panna)",
    desc_panna: "The gemstone of Mercury (Budh). Best for optimizing speech, mathematical intellect, and commercial communication.",
    gem_gomed: "Hessonite (Gomed)",
    desc_gomed: "The gemstone of Rahu. Highly effective for dispelling mental illusions, protection against sudden crises, and legal triumphs.",
    gem_munga: "Red Coral (Munga)",
    desc_munga: "The gemstone of Mars (Mangal). Promotes courage, physical vitality, self-confidence, and acts as an effective remedy for Manglik Dosh.",
    btn_inquire: "Inquire Now 🔱",
    gem_quality_title: "Our Quality & Purity Promise",
    gem_quality_desc: "The commercial market is flooded with synthetic, heated, and treated gemstones that yield zero astrological benefits. Our core foundation rests on absolute purity. We test every single gemstone through government-approved laboratories. You will receive an official certificate detailing its exact weight, refractive index, and natural origin.",
    gem_faq_title: "Gemstone Guidelines & FAQs",
    gem_q1: "Which gemstone should I wear?",
    gem_a1: "A gemstone should always be worn according to the lord of your Ascendant (Lagna) and Trikon (5th and 9th houses) in your birth chart. Wearing a gemstone without proper horoscope analysis can be detrimental.",
    gem_q2: "How are gemstones energetically activated?",
    gem_a2: "Before shipping, the gemstone is purified using holy Ganges water and raw milk. Following this, custom consecration (Pran Pratishtha) is performed through specific Vedic planetary mantras under your Name and Gotra.",
    gem_q3: "What is the difference between Heated and Unheated gemstones?",
    gem_a3: "Heated gemstones are artificially enhanced under high temperatures to improve clarity and color, which destroys their natural cosmic energies. For genuine astrological benefits, one must always wear unheated and untreated gemstones, which we provide.",

    // --- 3. Herbal Wellness Page ---
    herb_page_title: "Herbal Wellness & Health | MAHADEV ASTROLOGER MA",
    herb_hero_title: "AYURVEDIC HERBAL CARE",
    herb_hero_subtitle: "100% Pure, MSME & FSSAI Certified Natural Products",
    herb_intro_desc: "Vedic astrology and Ayurveda share an deeply close bond. MAHADEV ASTROLOGER MA brings you authentic herbs and planetary roots (Jadi), designed to harmonize your physical vitality and energetic fields. These selections are crafted solely for general wellness.",
    herb_collection: "Natural Wellness Roots",
    fssai_approved: "FSSAI APPROVED",
    herb_01_title: "Pure Shilajit / Ashwagandha",
    herb_01_desc: "An excellent natural dietary supplement designed to preserve physical endurance, mental vigor, and overall vitality naturally.",
    herb_02_title: "Grah Shanti Jadi (Planetary Roots)",
    herb_02_desc: "Authentic sacred herbs (such as Anantmool, Bidhara) for pacifying planetary afflictions. Wear them to rebalance your subtle cosmic energies.",
    herb_03_title: "Premium Brahmi & Shankhpushpi",
    herb_03_desc: "A natural aid to foster mental tranquility, memory retention, and cognitive focus. Strongly linked with Lunar and Mercurial vibrations.",
    btn_order: "ORDER NOW",
    herb_quality_title: "Authenticity & Disclaimer",
    herb_quality_desc: "All our specialized botanical roots and wellness supplements are compliant with the benchmarks set by MSME and FSSAI. Disclaimer: We do not assert any direct medical claims or guarantee treatments for chronic conditions. Our solutions strictly aim to improve general wellness and systemic baseline harmony.",
    herb_faq_title: "Herbal Wellness Guidelines & FAQs",
    herb_q1: "Are your wellness products legally certified?",
    herb_a1: "Yes, our establishment is officially registered under the Ministry of MSME, and all our natural dietary support items comply fully with the rigorous safety standards of FSSAI.",
    herb_q2: "Will these natural products cure any disease completely?",
    herb_a2: "No. These products are formulated exclusively to support your body's innate stamina, vital energy, and standard holistic health. If you suffer from a major medical illness, please seek guidance from a qualified doctor.",
    herb_q3: "How should the Grah Shanti Jadi be used effectively?",
    herb_a3: "A planetary root serves as an eco-friendly, accessible alternative to expensive gemstones. It is ritually wrapped in clean cotton string or cloth during an auspicious Muhurat and tied around the upper arm or neck to harmonize planetary influences.",

    // --- 4. Puja Kits Page ---
    puja_page_title: "Spiritual Puja & Vastu Kits | Energy Balancing - MAHADEV ASTROLOGER MA",
    puja_hero_title: "Puja & Energy Balancing Kits",
    puja_hero_subtitle: "Vedic Solutions for Wealth, Peace & Vastu Rectification",
    puja_intro_desc: "The structural energy fields of our living and commercial spaces cast a profound influence over our destiny. These customized invocation and Vastu kits curated by MAHADEV ASTROLOGER MA are firmly rooted in ancient Vedic sciences to dispel negative heavy fields and restore pure cosmic flow.",
    puja_collection: "Divine Energy Kits",
    kit_01_title: "Vastu Dosha Niwarak Kit",
    kit_01_desc: "A scientific balancing framework tailored for your property's 16 structural zones. Includes custom-selected geometric Yantras, natural earth salts, and space-cleansing elements.",
    kit_02_title: "Premium Monthly Puja Kit",
    kit_02_desc: "Pure, high-grade essentials assembled for your monthly home rituals. Contains high-end aromatic incense, pure Bhimseni camphor, organic cow ghee, and sacred havan ingredients.",
    kit_03_title: "Business Growth Energy Kit",
    kit_03_desc: "Engineered specifically to invoke professional abundance and financial protection. Assembles consecrated Gomti Chakras, spiritual Cowries, lotus seed garlands, and an energized Dhan Varsha Yantra.",
    puja_quality_title: "Ritual Consecration & Pure Standards",
    puja_quality_desc: "Every element and sacred geometric instrument provided by our Divine wisdom lab is thoroughly energized during strict planetary windows by Vedic ritualists. The specialized Vastu frameworks operate on spatial remediation theories to neutralize zoning blockages without requiring architectural alterations.",
    puja_faq_title: "Puja & Vastu Kits Guidelines & FAQs",
    puja_q1: "Where should the Vastu Dosha Niwarak Kit be ideally placed?",
    puja_a1: "It is best installed in the specific sector identified with an energetic layout flaw (such as an incorrectly aligned entrance or washroom). The spiritual core instruments contained within can also be permanently kept in your main temple alter.",
    puja_q2: "Are the sacred geometric Yantras pre-energized?",
    puja_a2: "Yes, prior to shipment, every single Yantra and material passes through explicit Vedic rituals and chant invocations to ensure they possess a functional baseline frequency upon arrival.",
    puja_q3: "What is the recommended method to set up the Business Growth Kit?",
    puja_a3: "This abundance kit should ideally be placed inside your main office cash box, trading drawer, or business altar on a Friday morning or during a benevolent Choghadiya window on top of a clean red silk cloth.",

    // --- 5. Rudraksha Page ---
    rudra_page_title: "Vedic Rudraksha | Original Nepal Beads - MAHADEV ASTROLOGER MA",
    rudra_hero_title: "SACRED NEPAL RUDRAKSHA",
    rudra_hero_subtitle: "Certified, Lab-Tested & Consecrated via Vedic Rituals",
    rudra_intro_desc: "Born from the divine tears of Lord Shiva, the sacred Rudraksha stands as a magnificent instrument for meditation, inner calm, and karmic mitigation. MAHADEV ASTROLOGER MA ensures access to purely organic, well-matured Nepalese and Indonesian beads, providing holistic neurological and subtle energy calibration.",
    rudra_collection: "Divine Rudraksha Collection",
    nepal_origin: "NEPAL ORIGIN",
    rudra_5m_title: "5 Mukhi Nepal Rudraksha",
    rudra_5m_desc: "Governed by Lord Jupiter (Brihaspati). Exceptional for accelerating intellectual growth, clearing life focus, and maintaining overall baseline health.",
    rudra_7m_title: "7 Mukhi Nepal Rudraksha",
    rudra_7m_desc: "Blest by Goddess Mahalakshmi and tied to Saturnian balancing. Indicated for opening clean wealth flows, vocational stability, and energetic protection.",
    rudra_gs_title: "Gauri Shankar Rudraksha",
    rudra_gs_desc: "The unified structural form of Lord Shiva and Goddess Parvati. A remarkably potent talisman for marital restoration, family alignment, and systemic interpersonal peace.",
    rudra_quality_title: "Authenticity & Radiograph Protocol",
    rudra_quality_desc: "Our brand strictly sources fully organic, wild-harvested Rudraksha beads. Every collector-grade specimen undergoes independent laboratory documentation and digital X-ray inspection to map internal seed cavities (compartments) before cataloging. Disclaimer: Wearing a Rudraksha is an ancient spiritual and wellness practice; it does not replace empirical clinical advice for serious medical conditions.",
    rudra_faq_title: "Rudraksha Guidelines & FAQs",
    rudra_q1: "How do you accurately verify a genuine Rudraksha?",
    rudra_a1: "An authentic natural bead houses precise internal compartments and matching seed pods that perfectly mirror the linear configurations (Mukhis) on its outer shell. The absolute diagnostic proof is achieved through high-definition radiograph screening at certified gem labs.",
    rudra_q2: "Are there strict guidelines for wearing a consecrated Rudraksha?",
    rudra_a2: "To protect its organic compound and energetic charge, it should be carefully removed prior to sleep, during visits to crematoriums, and during states of localized biological impurity. It should be put on again clean following your morning bath.",
    rudra_q3: "What does the energization process look like?",
    rudra_a3: "Prior to packaging, the bead undergoes purification using classical Panchamrita (organic raw milk, curd, honey, ghee, and Ganges water). This is followed by formal Pran Pratishtha chanting protocols employing cosmic seed mantras specific to the bead's facial facets mapped to your Name and Gotra."
  },

  // =====================================================================
  // 🕉️ HINDI TRANSLATIONS BLOCK
  // =====================================================================
  hi: {
    // --- 1. Main Shop Page ---
    shop_title: "महादेव एस्ट्रोलोज़र स्टोर",
    shop_subtitle: "100% प्रामाणिक आध्यात्मिक, ज्योतिषीय एवं हर्बल उत्पाद",
    shop_intro_desc: "प्रकृति और ऊर्जा का सही संतुलन आपके जीवन को सकारात्मक दिशा प्रदान कर सकता है। हमारे सभी उत्पाद वैदिक मंत्रों द्वारा अभिमंत्रित (ऊर्जावान) किए जाते हैं, ताकि आपको इनका पूर्ण लाभ प्राप्त हो सके।",
    trust_title: "हमारी प्रामाणिकता",
    fssai_reg_title: "एफएसएसएआई पंजीकृत",
    fssai_reg_desc: "हमारे सभी हर्बल और स्वास्थ्य उत्पाद एफएसएसएआई (FSSAI) द्वारा मान्यता प्राप्त हैं, जो इनकी शुद्धता और गुणवत्ता को प्रमाणित करते हैं।",
    lab_cert_title: "प्रयोगशाला प्रमाणित",
    lab_cert_desc: "सभी रत्न और रुद्राक्ष मान्यता प्राप्त प्रयोगशालाओं द्वारा प्रमाणित होते हैं। हम नकली उत्पादों के क्रय-विक्रय को पूर्णतः प्रतिबंधित करते हैं।",
    vedic_energized_title: "वैदिक अनुष्ठान द्वारा सिद्ध",
    vedic_energized_desc: "प्रेषण से पूर्व, प्रत्येक रत्न और यंत्र को आपके नाम और गोत्र के अनुसार विशिष्ट वैदिक मंत्रों द्वारा पूर्णतः अभिमंत्रित एवं सिद्ध (प्राण प्रतिष्ठा) किया जाता है।",
    divine_store: "दिव्य स्टोर श्रेणियाँ",
    cat_gemstones: "प्राकृतिक रत्न",
    desc_gemstones: "अपनी कुंडली के अनुकूल लैब-प्रमाणित रत्न प्राप्त करें, जो ग्रहों के दुष्प्रभाव को कम करके आपके जीवन में सौभाग्य लाते हैं।",
    cat_rudraksha: "दिव्य रुद्राक्ष",
    desc_rudraksha: "प्रामाणिक नेपाली एवं इंडोनेशियन रुद्राक्ष (1 से 14 मुखी), जो ध्यान, मानसिक शांति और उत्तम स्वास्थ्य के लिए अत्यंत लाभकारी हैं।",
    cat_herbs: "हर्बल आरोग्यता",
    desc_herbs: "प्राकृतिक जड़ी-बूटियां (मूल) और एफएसएसएआई प्रमाणित औषधियां, जो आपके शारीरिक और मानसिक स्वास्थ्य को संतुलित रखती हैं।",
    cat_energy_kits: "ऊर्जा किट्स एवं पूजन सामग्री",
    desc_energy_kits: "वास्तु सामग्री, सिद्ध यंत्र और पूजन किट, जो आपके गृह अथवा व्यावसायिक प्रतिष्ठान में सकारात्मक ऊर्जा का संचार करते हैं।",
    how_to_order_title: "आदेश प्रक्रिया (ऑर्डर कैसे करें)",
    step_01_label: "01. उत्पाद का चयन:",
    step_01_desc: "अपनी ज्योतिषीय आवश्यकता के अनुसार उचित रत्न, रुद्राक्ष या औषधीय जड़ी-बूटी का चयन करें।",
    step_02_label: "02. व्हाट्सएप संपर्क:",
    step_02_desc: "प्रत्येक उत्पाद के नीचे दिए गए 'ऑर्डर' बटन पर क्लिक करके सीधे हमारे व्हाट्सएप से जुड़ें।",
    step_03_label: "03. सुरक्षित भुगतान:",
    step_03_desc: "उत्पाद सुनिश्चित होने के पश्चात आप यूपीआई (UPI) अथवा बैंक ट्रांसफर के माध्यम से सुरक्षित भुगतान कर सकते हैं।",
    step_04_label: "04. सिद्धिकरण एवं वितरण:",
    step_04_desc: "वैदिक अनुष्ठान द्वारा सिद्ध करने के पश्चात, आपका उत्पाद 3 से 5 दिनों के भीतर आपके निवास स्थान पर सुरक्षित पहुंचा दिया जाएगा।",
    shop_faq_title: "अक्सर पूछे जाने वाले प्रश्न (FAQs)",
    shop_q1: "क्या सभी रत्न और रुद्राक्ष प्रामाणिक होते हैं?",
    shop_a1: "जी हाँ, हमारे संस्थान से प्राप्त प्रत्येक रत्न और रुद्राक्ष एक आधिकारिक लैब सर्टिफिकेट के साथ आता है, जिसमें उसके वजन, आकार, रंग और शुद्धता का संपूर्ण विवरण दर्ज होता है।",
    shop_q2: "रत्नों और रुद्राक्षों को अभिमंत्रित कैसे किया जाता है?",
    shop_a2: "वैदिक शास्त्रोक्त पद्धति के अनुसार, आपके नाम और गोत्र का संकल्प लेकर विशेष मंत्रों द्वारा प्राण-प्रतिष्ठा की जाती है, ताकि वह उत्पाद सीधे आपकी ऊर्जा और कुंडली चक्रों से जुड़ सके।",
    shop_q3: "हर्बल स्वास्थ्य उत्पाद किस प्रकार लाभकारी हैं?",
    shop_a3: "हमारे हर्बल उत्पाद ज्योतिषीय अनुसंधान और शास्त्रीय आयुर्वेद पर आधारित हैं। ये पूर्णतः एफएसएसएआई प्रमाणित हैं और इनका उपयोग कमजोर ग्रहों की शांति हेतु प्राकृतिक उपचार (जड़ी धारण) के रूप में किया जाता है。",

    // --- 2. Gemstones Page ---
    gem_title: "वैदिक नवग्रह रत्न",
    gem_subtitle: "100% शुद्ध, प्रमाणित एवं अभिमंत्रित रत्न",
    gem_intro_desc: "वैदिक ज्योतिष के अनुसार, प्रत्येक ग्रह एक निश्चित ब्रह्मांडीय ऊर्जा और किरणें उत्सर्जित करता है। जब कोई ग्रह कुंडली में निर्बल होता है, तो उस ग्रह से संबंधित शुद्ध रत्न धारण करने से उसकी दिव्य ऊर्जा में वृद्धि होती है। MAHADEV ASTROLOGER MA पर आपको केवल प्राकृतिक, बिना उपचारित (Unheated/Untreated) और लैब-प्रमाणित रत्न ही प्राप्त होंगे।",
    premium_gems_title: "प्राकृतिक नवग्रह रत्न श्रेणी",
    gem_pukhraj: "प्राकृतिक पुखराज रत्न",
    desc_pukhraj: "देवगुरु बृहस्पति का दिव्य रत्न। विद्या, बुद्धि, धन संचय और विवाह मार्ग में आ रही बाधाओं को दूर करने के लिए अत्यंत लाभकारी।",
    gem_neelam: "प्राकृतिक नीलम रत्न",
    desc_neelam: "शनि ग्रह का अत्यंत प्रभावशाली और तीव्र रत्न। व्यापार में उन्नति, शत्रु बाधा निवारण और मानसिक शांति के लिए उत्तम।",
    gem_manikya: "प्राकृतिक माणिक्य रत्न",
    desc_manikya: "नवग्रहों के राजा सूर्य देव का रत्न। आत्मविश्वास, नेतृत्व क्षमता (Leadership) और सरकारी कार्यों में अभूतपूर्व सफलता के लिए।",
    gem_panna: "प्राकृतिक पन्ना रत्न",
    desc_panna: "बुध ग्रह का प्रतिनिधि रत्न। वाणी, प्रखर बुद्धि, गणितीय कौशल और व्यापारिक संचार (Communication) को अनुकूल बनाने के लिए।",
    gem_gomed: "प्राकृतिक गोमेद रत्न",
    desc_gomed: "राहु ग्रह का रत्न। मानसिक दुविधा दूर करने, अचानक आने वाली आकस्मिक बाधाओं से रक्षा और कानूनी कार्यों में सफलता के लिए अत्यंत लाभकारी।",
    gem_munga: "प्राकृतिक मूँगा रत्न",
    desc_munga: "मंगल ग्रह का रत्न। साहस, ऊर्जा और आत्मविश्वास में वृद्धि के लिए। मांगलिक दोष निवारण और भूमि संबंधी लाभ के लिए सर्वश्रेष्ठ।",
    btn_inquire: "अभी परामर्श करें 🔱",
    gem_quality_title: "हमारे रत्नों की विशेषता एवं प्रामाणिकता",
    gem_quality_desc: "बाजार में अनेक कृत्रिम (Artificial) और हीटेड/ट्रीटेड रत्न उपलब्ध हैं, जिनका ज्योतिषीय लाभ शून्य होता है। हमारा सिद्धांत पूर्ण शुद्धता पर आधारित है। हम प्रत्येक रत्न को सरकारी मान्यता प्राप्त प्रयोगशाला से प्रमाणित करवाएं। आपको रत्न के साथ उसका वजन, रिफ्रैक्टिव इंडेक्स और प्राकृतिक शुद्धता का प्रमाण पत्र प्रदान किया जाता है।",
    gem_faq_title: "रत्न धारण मार्गदर्शिका एवं प्रश्नोत्तर",
    gem_q1: "मुझे कौन सा रत्न धारण करना चाहिए?",
    gem_a1: "रत्न सदैव अपनी जन्म-कुंडली के लग्न और त्रिकोण (पंचम और नवम भाव) के स्वामी ग्रहों के अनुकूल ही धारण करना उचित होता है। बिना सही कुंडली विश्लेषण के रत्न धारण करना विपरीत प्रभाव दे सकता है।",
    gem_q2: "रत्नों को जाग्रत या अभिमंत्रित कैसे किया जाता है?",
    gem_a2: "आपके पास भेजने से पूर्व, रत्न को गंगाजल और कच्चे दूध से शुद्ध किया जाता है। तत्पश्चात, आपके नाम और गोत्र का संकल्प लेकर संबंधित ग्रह के वैदिक मंत्रों द्वारा इसकी उचित प्राण-प्रतिष्ठा की जाती है।",
    gem_q3: "हीटेड (Heated) और अनहीटेड (Unheated) रत्नों में क्या अंतर है?",
    gem_a3: "हीटेड रत्नों का रंग और चमक बढ़ाने के लिए उन्हें कृत्रिम रूप से उच्च तापमान पर तपाया जाता है, जिससे उनकी प्राकृतिक ब्रह्मांडीय ऊर्जा नष्ट हो जाती है। ज्योतिषीय लाभ के लिए सदैव अनहीटेड (प्राकृतिक) रत्न ही धारण करना अनिवार्य है।",

    // --- 3. Herbal Wellness Page ---
    herb_page_title: "हर्बल वेलनेस एवं आरोग्यता | MAHADEV ASTROLOGER MA",
    herb_hero_title: "आयुर्वेदिक हर्बल आरोग्यता",
    herb_hero_subtitle: "100% शुद्ध, MSME एवं FSSAI प्रमाणित प्राकृतिक उत्पाद",
    herb_intro_desc: "वैदिक ज्योतिष और आयुर्वेद का अत्यंत घनिष्ठ संबंध है। MAHADEV ASTROLOGER MA आपके लिए लाए हैं शुद्ध जड़ी-बूटियाँ और ग्रह शांति मूल (जड़ें), जो आपके शारीरिक संतुलन और ऊर्जा को अनुकूल बनाए रखने में सहायक हैं। ये उत्पाद केवल सामान्य स्वास्थ्य (जनरल वेलनेस) के संवर्धन के लिए हैं।",
    herb_collection: "प्राकृतिक स्वास्थ्य संवर्धन मूल",
    fssai_approved: "FSSAI प्रमाणित",
    herb_01_title: "शुद्ध शिलाजीत / अश्वगंधा",
    herb_01_desc: "शारीरिक ऊर्जा, मानसिक ओज और जीवन शक्ति (Vitality) को प्राकृतिक रूप से बनाए रखने के लिए एक उत्तम स्वास्थ्य पूरक उत्पाद।",
    herb_02_title: "ग्रह शांति जड़ी (मूल)",
    herb_02_desc: "नवग्रहों की शांति के लिए विशेष प्रामाणिक जड़ी-बूटियाँ (जैसे अनंतमूल, विधारा)। ग्रहों के अशुभ प्रभाव को संतुलित करने हेतु धारण करें।",
    herb_03_title: "ब्राह्मी एवं शंखपुष्पी",
    herb_03_desc: "मानसिक शांति, स्मरण शक्ति और बौद्धिक एकाग्रता को बढ़ाने में सहायक। यह मुख्य रूप से चंद्रमा और बुध की ऊर्जा से संबंधित है।",
    btn_order: "अभी ऑर्डर करें",
    herb_quality_title: "प्रामाणिकता और अस्वीकरण (Disclaimer)",
    herb_quality_desc: "हमारी सभी जड़ी-बूटियाँ और आयुर्वेदिक स्वास्थ्य पूरक उत्पाद MSME एवं FSSAI (भारतीय खाद्य सुरक्षा और मानक प्राधिकरण) द्वारा निर्धारित मानकों के अनुरूप हैं। अस्वीकरण: हम किसी भी प्रकार के प्रत्यक्ष चिकित्सीय (Medical) उपचार का दावा नहीं करते हैं। ये उत्पाद किसी भी गंभीर शारीरिक या मानसिक रोग को पूर्णतः ठीक करने का आश्वासन नहीं देते। इनका उद्देश्य केवल आपके सामान्य स्वास्थ्य (General Wellness) का संवर्धन और शरीर में पंचतत्वों के संतुलन को बनाए रखना है।",
    herb_faq_title: "हर्बल आरोग्यता मार्गदर्शिका एवं प्रश्नोत्तर",
    herb_q1: "क्या आपके उत्पाद वैधानिक रूप से मान्यता प्राप्त हैं?",
    herb_a1: "जी हाँ, हमारा संस्थान भारत सरकार के MSME मंत्रालय के अंतर्गत पंजीकृत है और हमारे सभी आहार पूरक उत्पाद (Dietary Supplements) FSSAI के कड़े नियमों एवं मानकों का पूर्णतः पालन करते हैं।",
    herb_q2: "क्या इन स्वास्थ्य उत्पादों से कोई रोग पूर्ण रूप से ठीक हो सकता है?",
    herb_a2: "नहीं। ये उत्पाद केवल आपके शारीरिक बल, जीवनी ऊर्जा और सामान्य आरोग्य को संतुलित रखने के उद्देश्य से निर्मित किए गए हैं। यदि आप किसी गंभीर व्याधि या रोग से ग्रस्त हैं, तो उचित परामर्श के लिए अपने योग्य चिकित्सक से संपर्क अवश्य करें।",
    herb_q3: "ग्रह शांति जड़ी (मूल) का प्रयोग किस प्रकार किया जाता है?",
    herb_a3: "ग्रह शांति जड़ी बहुमूल्य रत्नों का एक अत्यंत सुलभ और प्राकृतिक शास्त्रोक्त विकल्प है। इसे एक निश्चित शुभ मुहूर्त में, सूती धागे अथवा वस्त्र में लपेटकर दाहिनी भुजा या गले में धारण किया जाता है, जिससे ग्रह की रश्मियों का सकारात्मक प्रभाव शरीर पर बना रहे।",

    // --- 4. Puja Kits Page ---
    puja_page_title: "आध्यात्मिक पूजन एवं वास्तु किट्स | ऊर्जा संतुलन - MAHADEV ASTROLOGER MA",
    puja_hero_title: "पूजन एवं ऊर्जा संतुलन किट्स",
    puja_hero_subtitle: "समृद्धि, शांति और वास्तु संतुलन के लिए प्रामाणिक वैदिक समाधान",
    puja_intro_desc: "हमारे निवास और व्यावसायिक प्रतिष्ठान की ऊर्जा हमारे संपूर्ण जीवन पर सीधा प्रभाव डालती है। MAHADEV ASTROLOGER MA द्वारा प्रस्तुत ये विशेष पूजन एवं वास्तु किट्स प्राचीन वैदिक सिद्धांतों और वैज्ञानिक शोध पर आधारित हैं। इनका मुख्य उद्देश्य परिसरों से नकारात्मक ऊर्जा को दूर कर सकारात्मक ब्रह्मांडीय ऊर्जा का पूर्ण संचार करना है।",
    puja_collection: "दिव्य ऊर्जा एवं पूजन किट्स",
    kit_01_title: "वास्तु दोष निवारक किट",
    kit_01_desc: "आपके भवन के 16-ज़ोन ऊर्जा संतुलन के लिए वैज्ञानिक उपचार। इस किट में दोष निवारक अनुशंसित यंत्र, प्राकृतिक अर्थ साल्ट और परिसर शुद्धिकरण सामग्री शामिल है।",
    kit_02_title: "प्रीमियम मासिक पूजन किट",
    kit_02_desc: "नियमित मासिक अनुष्ठानों हेतु शुद्ध एवं सात्विक सामग्री। इस सेट में प्रीमियम गुणवत्ता की धूप, शुद्ध भीमसेनी कपूर, गोघृत (गाय का घी) और सिद्ध हवन सामग्री उपलब्ध है।",
    kit_03_title: "व्यापार वृद्धि ऊर्जा किट",
    kit_03_desc: "व्यापारिक प्रतिष्ठानों में निरंतर उन्नति और लक्ष्मी कृपा हेतु। इसमें सिद्ध गोमती चक्र, कौड़ी, कमलगट्टा और धन वर्षा यंत्र का विशेष शास्त्रोक्त संयोजन है।",
    btn_order: "अभी खरीदें 🔱",
    puja_quality_title: "ऊर्जीकरण (Pran Pratishtha) एवं सामग्री शुद्धता",
    puja_quality_desc: "हमारे संस्थान द्वारा प्रदान की जाने वाली सभी पूजन सामग्रियां और यंत्र शुभ मुहूर्त में वैदिक विद्वानों द्वारा पूर्णतः अभिमंत्रित और सिद्ध किए जाते हैं। इन वास्तु किट्स का उपयोग विशेष रूप से परिसर के 16-ज़ोन ऊर्जा विश्लेषण के आधार पर किया जाता है, ताकि विभिन्न दिशाओं के दोषों को बिना किसी तोड़-फोड़ के प्रभावी रूप से संतुलित किया जा सके।",
    puja_faq_title: "पूजन एवं वास्तु किट्स से संबंधित प्रश्नोत्तर",
    puja_q1: "वास्तु दोष निवारक किट का प्रयोग किस स्थान पर करना चाहिए?",
    puja_a1: "इसे अपने निवास स्थान या व्यावसायिक परिसर के उस विशेष भाग में स्थापित करना श्रेयस्कर होता है जहाँ ऊर्जा असंतुलित हो (जैसे दूषित दिशा में मुख्य प्रवेश द्वार या शौचालय)। किट के भीतर आने वाले सिद्ध यंत्रों को आप अपने पवित्र पूजा गृह में भी स्थापित कर सकते हैं।",
    puja_q2: "क्या इन किट्स के यंत्र पहले से अभिमंत्रित (Pre-energized) होते हैं?",
    puja_a2: "जी हाँ, आपके पते पर प्रेषित करने से पूर्व, प्रत्येक यंत्र और दिव्य सामग्री की वैदिक मन्त्रों एवं पौराणिक सूक्तों द्वारा विधिवत प्राण-प्रतिष्ठा की जाती है, ताकि परिसर में स्थापित होते ही आपको इनका पूर्ण और त्वरित शुभ फल प्राप्त हो सके।",
    puja_q3: "व्यापार वृद्धि किट को स्थापित करने की शास्त्रोक्त विधि क्या है?",
    puja_a3: "इस किट को विशेष रूप से अपने कार्यस्थल (Office), दुकान की तिजोरी (Cash Box) अथवा व्यापारिक प्रतिष्ठान के मुख्य पूजा स्थान पर शुक्रवार के दिन या किसी अन्य शुभ चौघड़िये में लाल रेशमी वस्त्र के ऊपर स्थापित करना सर्वोत्तम माना जाता है।",

    // --- 5. Rudraksha Page ---
    rudra_page_title: "वैदिक रुद्राक्ष | MAHADEV ASTROLOGER MA",
    rudra_hero_title: "पावन नेपाल रुद्राक्ष",
    rudra_hero_subtitle: "प्रमाणित, लैब-परीक्षित एवं वैदिक मंत्रों द्वारा अभिमंत्रित",
    rudra_intro_desc: "भगवान शिव के अश्रुबिंदुओं से उत्पन्न रुद्राक्ष ध्यान, मानसिक शांति और ग्रह दोष निवारण का एक अलौकिक व अचूक माध्यम है। MAHADEV ASTROLOGER MA पर आपको केवल प्राकृतिक और पूर्णतः शुद्ध नेपाली एवं इंडोनेशियन मुखी रुद्राक्ष ही प्राप्त होंगे, जो आपके शारीरिक संतुलन और सामान्य स्वास्थ्य के संवर्धन के लिए अत्यंत लाभकारी हैं।",
    rudra_collection: "दिव्य रुद्राक्ष संग्रह",
    nepal_origin: "नेपाल उत्पत्ति",
    rudra_5m_title: "5 मुखी नेपाल रुद्राक्ष",
    rudra_5m_desc: "देवगुरु बृहस्पति का प्रतिनिधित्व। मानसिक शांति, उच्च शिक्षा, एकाग्रता और सामान्य स्वास्थ्य के संतुलन के लिए सर्वश्रेष्ठ प्राकृतिक मनका।",
    rudra_7m_title: "7 मुखी नेपाल रुद्राक्ष",
    rudra_7m_desc: "माता महालक्ष्मी और शनि देव की कृपा से संबंधित। जीवन में निरंतर धन आगमन, व्यापारिक समृद्धि और नकारात्मक ऊर्जा से रक्षा के लिए उत्तम।",
    rudra_gs_title: "गौरी शंकर रुद्राक्ष",
    rudra_gs_desc: "भगवान शिव और आद्यशक्ति माता पार्वती का संयुक्त साकार स्वरूप। पारिवारिक संतुलन, आपसी सामंजस्य और सुखद वैवाहिक जीवन के लिए अत्यंत शक्तिशाली।",
    rudra_quality_title: "प्रामाणिकता और अस्वीकरण (Disclaimer)",
    rudra_quality_desc: "हम केवल पूर्ण रूप से विकसित, परिपक्व और प्राकृतिक रुद्राक्ष ही प्रदान करते हैं। प्रत्येक मनके (Bead) की शुद्धता और आंतरिक बनावट की पुष्टि डिजिटल एक्स-रे (X-Ray) एवं प्रयोगशाला परीक्षण द्वारा की जाती है, ताकि इसके भीतर के प्राकृतिक कक्षों (Compartments) की सत्यता सुनिश्चित की जा सके। अस्वीकरण: रुद्राक्ष धारण करना एक प्राचीन वैदिक, सांस्कृतिक और आध्यात्मिक प्रक्रिया है। हम किसी भी प्रकार के प्रत्यक्ष चिकित्सीय (Medical) उपचार या रोग मुक्ति का दावा नहीं करते हैं। यह उत्पाद किसी गंभीर रोग को ठीक करने की वैज्ञानिक गारंटी नहीं देता है।",
    rudra_faq_title: "रुद्राक्ष मार्गदर्शिका एवं प्रश्नोत्तर",
    rudra_q1: "असली रुद्राक्ष की पहचान किस प्रकार की जाती है?",
    rudra_a1: "प्राकृतिक रूप से प्रामाणिक रुद्राक्ष के भीतर उतने ही बीज (Seeds) या कक्ष बने होते हैं, जितने उसके बाहरी धरातल पर मुख (Lines) दिखाई देते हैं। इसकी १००% सटीक वैज्ञानिक पुष्टि केवल मान्यता प्राप्त प्रयोगशाला में एक्स-रे परीक्षण द्वारा ही संभव है।",
    rudra_q2: "क्या रुद्राक्ष धारण करने के कुछ विशेष नियम हैं?",
    rudra_a2: "जी हाँ, पूर्ण आध्यात्मिक एवं सात्विक लाभ प्राप्त करने हेतु इसे रात्रि में सोते समय, शव यात्रा (श्मशान भूमि) में, और अन्य अशुद्ध स्थानों पर जाने से पूर्व उतार देना शास्त्रसम्मत माना जाता है। प्रातः काल नित्य क्रिया और स्नान के पश्चात इसे पुनः धारण करना चाहिए।",
    rudra_q3: "रुद्राक्ष को जाग्रत या अभिमंत्रित किस प्रकार किया जाता है?",
    rudra_a3: "संस्थान से प्रेषित करने से पूर्व रुद्राक्ष का पंचामृत (दूध, दही, घृत, शहद, गंगाजल) से अभिषेक किया जाता है। तत्पश्चात, आपके नाम और गोत्र का संकल्प लेकर 'ॐ नमः शिवाय' और विशिष्ट मुखी के बीज मंत्रों का वैदिक ब्राह्मणों द्वारा जाप करके इसकी प्राण-प्रतिष्ठा की जाती है।"
  }
};
