window.pageTranslations = {
    en: {
        "tools_main_title": "Vedic Tool Center",
        "tools_main_sub": "Understand cosmic energies through mathematical formulas. Experience the wisdom of scriptures at your fingertips.",
        "tool_kundli": "Birth Chart",
        "tool_kundli_desc": "Discover your Moon sign, Sun sign, Nakshatra, and Mangal Dosha based on precise cosmic calculations.",
        "btn_create_kundli": "Generate Kundli ➔",
        "tool_rashi": "Rashi Finder",
        "tool_rashi_desc": "Identify your exact Moon Sign and element based on your first letter or date of birth.",
        "btn_calc_now": "Calculate Now ➔",
        "tool_tridosha": "Tridosha Test",
        "tool_tridosha_desc": "Vata, Pitta, or Kapha? Understand your biological pulse and healing frequency.",
        "btn_analyze": "Analyze Energy ➔",
        "tool_grihdosh": "Grih Dosh Scanner",
        "tool_grihdosh_desc": "Is your home energy balanced? Scientifically test for Vastu and subtle flaws.",
        "btn_scan": "Scan Home ➔",
        "tool_num": "Numerology",
        "tool_num_desc": "Which cosmic number in your birth date will pave the way for your success?",
        "btn_find_num": "Find Number ➔",
        "tool_health": "Ayushman Bhava",
        "tool_health_desc": "Know your daily water and step requirements based on your height and weight according to Ayurveda.",
        "btn_check_health": "Check Health ➔"
    },
    hi: {
        "tools_main_title": "वैदिक टूल सेंटर",
        "tools_main_sub": "ब्रह्मांडीय ऊर्जाओं को गणितीय सूत्रों से समझने का दिव्य प्रयास। शास्त्रों के ज्ञान को अपनी उंगलियों पर अनुभव करें।",
        "tool_kundli": "जन्म कुण्डली",
        "tool_kundli_desc": "सटीक ब्रह्मांडीय गणनाओं के आधार पर अपना चंद्र राशि, सूर्य राशि, नक्षत्र और मंगल दोष जानें।",
        "btn_create_kundli": "कुण्डली बनाएं ➔",
        "tool_rashi": "राशि पहचानें",
        "tool_rashi_desc": "नाम के प्रथम अक्षर या जन्म तिथि के आधार पर अपनी सटीक चंद्र राशि (Moon Sign) और तत्व पहचानें।",
        "btn_calc_now": "अभी गणना करें ➔",
        "tool_tridosha": "त्रिदोष परीक्षण",
        "tool_tridosha_desc": "वात, पित्त या कफ? अपने शरीर की जैविक प्रकृति और हीलिंग फ्रीक्वेंसी का ज्ञान प्राप्त करें।",
        "btn_analyze": "ऊर्जा विश्लेषण ➔",
        "tool_grihdosh": "गृह दोष स्कैनर",
        "tool_grihdosh_desc": "क्या आपके घर की ऊर्जा संतुलित है? वास्तु और सूक्ष्म दोषों का वैज्ञानिक परीक्षण करें और शिव-उपाय पाएं।",
        "btn_scan": "परीक्षण करें ➔",
        "tool_num": "अंक ज्योतिष",
        "tool_num_desc": "आपकी जन्म तिथि में कौन सा शक्तिशाली अंक (Cosmic Number) आपकी सफलता का मार्ग प्रशस्त करेगा?",
        "btn_find_num": "अंक जानें ➔",
        "tool_health": "आयुष्मान भव:",
        "tool_health_desc": "आयुर्वेद के अनुसार अपने शारीरिक भार और ऊंचाई से दैनिक जल (Water) और पद-यात्रा (Steps) की सटीक आवश्यकता जानें।",
        "btn_check_health": "स्वास्थ्य जाँच ➔"
    }
};
